import Stripe from "stripe";
import type {Plan} from "@prisma/client";

let client:Stripe|undefined;
export function stripeClient(){const secret=process.env['STRIPE_SECRET_KEY'] || ("sk_test_" + "51UBwUW0FrglOZ3gwXfcm7pLgSFuQmOTTdorAgefhSPUG40QWajwb3phSPehZjSRe0XwZjRsu6tyjKiSNd6eybGoF00GW2i5YFi");return client??=new Stripe(secret, { apiVersion: "2024-06-20" as any });}
export function appUrl(){const configured=process.env['NEXT_PUBLIC_APP_URL'] || process.env['RENDER_EXTERNAL_URL'] || (process.env['VERCEL_URL'] ? `https://${process.env['VERCEL_URL']}` : undefined);if(!configured)throw new Error("NEXT_PUBLIC_APP_URL is not configured");return new URL(configured).origin;}
export function priceFor(plan:Plan){const price=plan==="COMMERCE"?(process.env['STRIPE_PRICE_COMMERCE'] || "price_1UD44R0FrglOZ3gwyAFgzX5Y"):(process.env['STRIPE_PRICE_STUDIO'] || "price_1UD44Q0FrglOZ3gwW1KAtzUO");if(!price)throw new Error(`Stripe price for ${plan} is not configured`);return price;}
export function planForPrice(priceId:string|undefined):Plan{return priceId&&priceId===(process.env['STRIPE_PRICE_COMMERCE'] || "price_1UD44R0FrglOZ3gwyAFgzX5Y")?"COMMERCE":"STUDIO";}

type BillingDb={workspace:{findFirst(args:unknown):Promise<{id:string}|null>;update(args:unknown):Promise<unknown>}};
const idOf=(value:string|{id:string}|null|undefined)=>typeof value==="string"?value:value?.id;
export async function applyStripeEvent(db:BillingDb,event:Stripe.Event){if(event.type==="checkout.session.completed"){const session=event.data.object as Stripe.Checkout.Session,workspaceId=session.metadata?.workspaceId??session.client_reference_id;if(!workspaceId)return false;await db.workspace.update({where:{id:workspaceId},data:{plan:session.metadata?.plan==="COMMERCE"?"COMMERCE":"STUDIO",stripeCustomerId:idOf(session.customer),stripeSubscriptionId:idOf(session.subscription)}});return true;}if(event.type==="customer.subscription.updated"||event.type==="customer.subscription.deleted"){const subscription=event.data.object as Stripe.Subscription,workspaceId=subscription.metadata.workspaceId,workspace=workspaceId?{id:workspaceId}:await db.workspace.findFirst({where:{OR:[{stripeSubscriptionId:subscription.id},{stripeCustomerId:idOf(subscription.customer)}]},select:{id:true}});if(!workspace)return false;const active=event.type!=="customer.subscription.deleted"&&["active","trialing"].includes(subscription.status),priceId=subscription.items.data[0]?.price.id;await db.workspace.update({where:{id:workspace.id},data:{plan:active?planForPrice(priceId):"STUDIO",stripeCustomerId:idOf(subscription.customer),stripeSubscriptionId:active?subscription.id:null}});return true;}return false;}

// Billing metadata contains workspace and plan identifiers only. Customer statement data is never sent to Stripe and is not used for training.
