import type {ParseResult,RawRow} from "./types";
export const MAX_FILE_BYTES=20*1024*1024;
export const clean=(value:string|undefined)=>value?.trim().replace(/\s+/g," ")??"";
export const headerKey=(value:string)=>clean(value).toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
function parseLine(line:string,delimiter=","){const values:string[]=[];let value="",quoted=false;for(let index=0;index<line.length;index++){const char=line[index];if(char==='"'&&quoted&&line[index+1]==='"'){value+='"';index++;}else if(char==='"')quoted=!quoted;else if(char===delimiter&&!quoted){values.push(value);value="";}else value+=char;}if(quoted)throw new Error("Unclosed quoted field");values.push(value);return values;}
function detectDelimiter(header:string):string{const counts={",":0,";":0,"\t":0};for(const char of header)if(char in counts)(counts as Record<string,number>)[char]++;if(counts[";"]>counts[","]&&counts[";"]>=counts["\t"])return";";if(counts["\t"]>counts[","]&&counts["\t"]>counts[";"])return"\t";return",";}
export function readCsv(file:Buffer,filename:string):ParseResult<RawRow>{if(file.byteLength>MAX_FILE_BYTES)return{rows:[],errors:[{rowNumber:0,message:`${filename} exceeds the 20MB limit`}]};const text=file.toString("utf8").replace(/^\uFEFF/,"");const rawLines=text.split(/\r\n|\r|\n/);const lines=rawLines.map(line=>{const trimmed=line.trim();if(trimmed.length>=2&&trimmed.startsWith('"')&&trimmed.endsWith('"')&&!trimmed.slice(1,-1).includes('"'))return trimmed.slice(1,-1);return line;});const delimiter=detectDelimiter(lines[0]??"");let headers:string[];try{headers=parseLine(lines[0]??"",delimiter);}catch(error){return{rows:[],errors:[{rowNumber:1,message:error instanceof Error?error.message:"Invalid CSV header"}]};}if(headers.length<2)return{rows:[],errors:[{rowNumber:1,message:"CSV must contain at least 2 columns (commas, semicolons, or tabs accepted)"}]};const rows:RawRow[]=[],errors:{rowNumber:number;message:string}[]=[];for(let index=1;index<lines.length;index++){if(!lines[index].trim())continue;try{const values=parseLine(lines[index],delimiter);const raw:RawRow={};headers.forEach((header,column)=>raw[clean(header)]=clean(values[column]));rows.push(raw);}catch(error){errors.push({rowNumber:index+1,message:error instanceof Error?error.message:"Invalid CSV row"});}}return{rows,errors};}
export function findHeader(raw:RawRow,aliases:string[]){const byKey=new Map(Object.keys(raw).map(key=>[headerKey(key),key]));for(const alias of aliases){const actual=byKey.get(headerKey(alias));if(actual!==undefined)return actual;}return undefined;}
export function value(raw:RawRow,aliases:string[]){const header=findHeader(raw,aliases);return header===undefined?"":clean(raw[header]);}
