import { randomUUID, createHash } from 'node:crypto';
const id=()=>randomUUID(), now=()=>new Date().toISOString();
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const n=x=>{const v=Number(x);if(!Number.isFinite(v)||v<0)throw Error('INVALID_QUANTITY');return v};
export class CapTableService{
 constructor({audit,programmable}={}){this.audit=audit;this.programmable=programmable;this.classes=new Map();this.entries=[];this.actions=[];this.reconciliations=[]}
 createShareClass(input,actor='system'){
  if(!input.issuerId||!input.securityId||!input.name)throw Error('ISSUER_SECURITY_NAME_REQUIRED');if(this.classes.has(input.securityId))throw Error('SHARE_CLASS_EXISTS');
  const c={id:id(),issuerId:input.issuerId,securityId:input.securityId,name:input.name,currency:input.currency||'USD',authorized:n(input.authorized??0),reserved:n(input.reserved??0),parValueMinor:Number(input.parValueMinor||0),rights:input.rights||{},createdAt:now(),createdBy:actor};this.classes.set(c.securityId,c);this.#audit('CAP_TABLE_SHARE_CLASS_CREATED',actor,c.id,{issuerId:c.issuerId,securityId:c.securityId});return c
 }
 shareClass(securityId){const c=this.classes.get(securityId);if(!c)throw Error('SHARE_CLASS_NOT_FOUND');return c}
 issue(input,actor='system'){const c=this.shareClass(input.securityId);if(c.issuerId!==input.issuerId)throw Error('ISSUER_MISMATCH');const q=n(input.quantity);if(!q)throw Error('QUANTITY_REQUIRED');const issued=this.totalIssued(input.issuerId,input.securityId);if(c.authorized&&issued+q>c.authorized)throw Error('AUTHORIZED_SHARES_EXCEEDED');return this.#entry('ISSUE',{...input,quantity:q,toOwnerId:input.ownerId},actor)}
 transfer(input,actor='system'){
  const q=n(input.quantity);if(!q)throw Error('QUANTITY_REQUIRED');this.shareClass(input.securityId);if(!input.fromOwnerId||!input.toOwnerId)throw Error('TRANSFER_PARTIES_REQUIRED');if(this.balance(input.issuerId,input.securityId,input.fromOwnerId)<q)throw Error('INSUFFICIENT_SHARES');
  if(input.programDecision&&input.programDecision.decision!=='ALLOW')throw Error('PROGRAMMABLE_OWNERSHIP_DENIED');if(input.requireProgramGate!==false&&!input.programDecision)throw Error('PROGRAMMABLE_OWNERSHIP_DECISION_REQUIRED');
  return this.#entry('TRANSFER',{...input,quantity:q},actor)
 }
 cancel(input,actor='system'){const q=n(input.quantity);if(this.balance(input.issuerId,input.securityId,input.ownerId)<q)throw Error('INSUFFICIENT_SHARES');return this.#entry('CANCEL',{...input,quantity:q,fromOwnerId:input.ownerId},actor)}
 treasury(input,actor='system'){const q=n(input.quantity);if(this.balance(input.issuerId,input.securityId,input.ownerId)<q)throw Error('INSUFFICIENT_SHARES');return this.#entry('TREASURY',{...input,quantity:q,fromOwnerId:input.ownerId,toOwnerId:`TREASURY:${input.issuerId}`},actor)}
 balance(issuerId,securityId,ownerId,at=null){const t=at?Date.parse(at):Infinity;let v=0;for(const e of this.entries){if(e.issuerId!==issuerId||e.securityId!==securityId||Date.parse(e.effectiveAt)>t)continue;if(e.type==='ISSUE'&&e.toOwnerId===ownerId)v+=e.quantity;if(e.type==='TRANSFER'||e.type==='TREASURY'){if(e.fromOwnerId===ownerId)v-=e.quantity;if(e.toOwnerId===ownerId)v+=e.quantity}if(e.type==='CANCEL'&&e.fromOwnerId===ownerId)v-=e.quantity}return v}
 holders(issuerId,securityId,at=null){const owners=new Set();for(const e of this.entries.filter(e=>e.issuerId===issuerId&&e.securityId===securityId)){if(e.fromOwnerId)owners.add(e.fromOwnerId);if(e.toOwnerId)owners.add(e.toOwnerId)}return [...owners].map(ownerId=>({ownerId,quantity:this.balance(issuerId,securityId,ownerId,at)})).filter(x=>x.quantity>0)}
 totalIssued(issuerId,securityId,at=null){return this.holders(issuerId,securityId,at).reduce((s,x)=>s+x.quantity,0)}
 snapshot(issuerId,at=now()){const classes=[...this.classes.values()].filter(c=>c.issuerId===issuerId);const rows=classes.map(c=>({securityId:c.securityId,name:c.name,authorized:c.authorized,reserved:c.reserved,issued:this.totalIssued(issuerId,c.securityId,at),holders:this.holders(issuerId,c.securityId,at)}));const issued=rows.reduce((s,r)=>s+r.issued,0),reserved=rows.reduce((s,r)=>s+r.reserved,0);return{issuerId,at,issued,reserved,fullyDiluted:issued+reserved,shareClasses:rows,snapshotHash:hash({issuerId,at,rows})}}
 recordCorporateAction(input,actor='system'){this.shareClass(input.securityId);const a={id:id(),issuerId:input.issuerId,securityId:input.securityId,type:input.type,payload:input.payload||{},effectiveAt:input.effectiveAt||now(),status:'RECORDED',createdAt:now(),createdBy:actor};this.actions.push(a);this.#audit('CAP_TABLE_CORPORATE_ACTION_RECORDED',actor,a.id,{securityId:a.securityId,type:a.type});return a}
 reconcile(input,actor='system'){const internal=this.holders(input.issuerId,input.securityId);const external=new Map((input.authoritativeHoldings||[]).map(x=>[x.ownerId,n(x.quantity)]));const owners=new Set([...internal.map(x=>x.ownerId),...external.keys()]);const differences=[...owners].map(ownerId=>({ownerId,internal:internal.find(x=>x.ownerId===ownerId)?.quantity||0,authoritative:external.get(ownerId)||0})).filter(x=>x.internal!==x.authoritative).map(x=>({...x,delta:x.authoritative-x.internal}));const r={id:id(),issuerId:input.issuerId,securityId:input.securityId,source:input.source||'AUTHORITATIVE_ADAPTER',status:differences.length?'MISMATCH':'MATCH',differences,sourceHash:hash(input.authoritativeHoldings||[]),createdAt:now(),createdBy:actor};this.reconciliations.push(r);this.#audit('CAP_TABLE_RECONCILED',actor,r.id,{securityId:r.securityId,status:r.status,differences:differences.length});return r}
 ledger(issuerId,securityId){return this.entries.filter(e=>(!issuerId||e.issuerId===issuerId)&&(!securityId||e.securityId===securityId))}
 #entry(type,input,actor){const previous=this.entries.at(-1)?.entryHash||null;const base={id:id(),type,issuerId:input.issuerId,securityId:input.securityId,fromOwnerId:input.fromOwnerId||null,toOwnerId:input.toOwnerId||null,quantity:input.quantity,effectiveAt:input.effectiveAt||now(),reference:input.reference||null,programDecisionId:input.programDecision?.id||null,previousHash:previous,createdAt:now(),createdBy:actor};const e={...base,entryHash:hash(base)};this.entries.push(e);this.#audit(`CAP_TABLE_${type}`,actor,e.id,{issuerId:e.issuerId,securityId:e.securityId,quantity:e.quantity,entryHash:e.entryHash});return e}
 #audit(type,actor,subjectId,metadata){this.audit?.append({type,actor,subjectId,metadata})}
}
