import { randomUUID, createHash } from 'node:crypto';
const id=()=>randomUUID(), now=()=>new Date().toISOString();
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const pos=(x,n)=>{const v=Number(x);if(!Number.isFinite(v)||v<=0)throw Error(`INVALID_${n}`);return v};
export class LiquidityService{
 constructor({audit,capTable,pricing,preTradeGate}={}){this.audit=audit;this.capTable=capTable;this.pricing=pricing;this.preTradeGate=preTradeGate;this.orders=new Map();this.trades=[];this.rfqs=new Map();this.venues=new Map();this.alerts=[]}
 registerVenue(input,actor='system'){if(!input.name)throw Error('VENUE_NAME_REQUIRED');const v={id:input.id||id(),name:input.name,type:input.type||'INTERNAL',status:input.status||'ACTIVE',capabilities:input.capabilities||['LIMIT'],metadata:input.metadata||{},createdAt:now(),createdBy:actor};this.venues.set(v.id,v);this.#audit('LIQUIDITY_VENUE_REGISTERED',actor,v.id,{name:v.name,type:v.type});return v}
 place(input,actor='system'){
  this.#security(input.securityId);if(!['BUY','SELL'].includes(input.side))throw Error('INVALID_SIDE');const type=input.type||'LIMIT';if(!['LIMIT','MARKET'].includes(type))throw Error('INVALID_ORDER_TYPE');const quantity=pos(input.quantity,'QUANTITY');const priceMinor=type==='LIMIT'?pos(input.priceMinor,'PRICE'):null;
  const gate=this.#gate({...input,quantity,priceMinor});if(gate.decision!=='ALLOW')throw Object.assign(Error('PRE_TRADE_GATE_DENIED'),{details:gate});
  const o={id:id(),clientOrderId:input.clientOrderId||null,participantId:input.participantId,securityId:input.securityId,issuerId:input.issuerId||this.capTable?.shareClass(input.securityId)?.issuerId||null,side:input.side,type,quantity,remainingQuantity:quantity,priceMinor,currency:input.currency||this.capTable?.shareClass(input.securityId)?.currency||'USD',timeInForce:input.timeInForce||'GTC',status:'OPEN',venueId:input.venueId||'GOX_INTERNAL',gate,createdAt:now(),updatedAt:now(),createdBy:actor};o.orderHash=hash(o);this.orders.set(o.id,o);this.#audit('LIQUIDITY_ORDER_ACCEPTED',actor,o.id,{securityId:o.securityId,side:o.side,quantity:o.quantity,orderHash:o.orderHash});if(input.autoMatch!==false)this.match(o.securityId,actor);return o
 }
 cancel(orderId,actor='system'){const o=this.#order(orderId);if(!['OPEN','PARTIALLY_FILLED'].includes(o.status))throw Error('ORDER_NOT_CANCELABLE');o.status='CANCELED';o.updatedAt=now();this.#audit('LIQUIDITY_ORDER_CANCELED',actor,o.id,{remainingQuantity:o.remainingQuantity});return o}
 book(securityId){this.#security(securityId);const open=[...this.orders.values()].filter(o=>o.securityId===securityId&&['OPEN','PARTIALLY_FILLED'].includes(o.status));return{securityId,bids:open.filter(o=>o.side==='BUY').sort((a,b)=>(b.priceMinor??Infinity)-(a.priceMinor??Infinity)||Date.parse(a.createdAt)-Date.parse(b.createdAt)),asks:open.filter(o=>o.side==='SELL').sort((a,b)=>(a.priceMinor??0)-(b.priceMinor??0)||Date.parse(a.createdAt)-Date.parse(b.createdAt))}}
 match(securityId,actor='matching-engine'){const made=[];while(true){const {bids,asks}=this.book(securityId),b=bids[0],s=asks[0];if(!b||!s)break;const crosses=b.type==='MARKET'||s.type==='MARKET'||b.priceMinor>=s.priceMinor;if(!crosses)break;const quantity=Math.min(b.remainingQuantity,s.remainingQuantity),priceMinor=this.#executionPrice(b,s);const integrity=this.#integrity(securityId,priceMinor,b,s);if(integrity.block){this.#alert(securityId,'MATCH_REVIEW_REQUIRED',{buyOrderId:b.id,sellOrderId:s.id,...integrity},actor);break}const base={id:id(),securityId,issuerId:b.issuerId||s.issuerId,buyOrderId:b.id,sellOrderId:s.id,buyerId:b.participantId,sellerId:s.participantId,quantity,priceMinor,currency:b.currency,status:'MATCHED_UNSETTLED',venueId:b.venueId===s.venueId?b.venueId:'GOX_INTERNAL',matchedAt:now(),integrityFlags:integrity.flags};const t={...base,tradeHash:hash(base)};this.trades.push(t);this.#fill(b,quantity);this.#fill(s,quantity);this.pricing?.observe({securityId,type:'TRADE',priceMinor,quantity,currency:t.currency,source:'GOX_LIQUIDITY',sourceRef:t.id},actor);this.#audit('LIQUIDITY_TRADE_MATCHED',actor,t.id,{securityId,quantity,priceMinor,tradeHash:t.tradeHash});made.push(t)}return made}
 trade(tradeId){const t=this.trades.find(x=>x.id===tradeId);if(!t)throw Error('TRADE_NOT_FOUND');return t}
 tradesFor(securityId){return this.trades.filter(t=>!securityId||t.securityId===securityId)}
 createRFQ(input,actor='system'){this.#security(input.securityId);const r={id:id(),requesterId:input.requesterId,securityId:input.securityId,side:input.side,quantity:pos(input.quantity,'QUANTITY'),currency:input.currency||this.capTable?.shareClass(input.securityId)?.currency||'USD',minimumFill:Number(input.minimumFill||0),expiresAt:input.expiresAt||new Date(Date.now()+300000).toISOString(),status:'OPEN',invitedProviders:input.invitedProviders||[],quotes:[],createdAt:now(),createdBy:actor};if(!['BUY','SELL'].includes(r.side))throw Error('INVALID_SIDE');this.rfqs.set(r.id,r);this.#audit('LIQUIDITY_RFQ_CREATED',actor,r.id,{securityId:r.securityId,quantity:r.quantity});return r}
 quoteRFQ(rfqId,input,actor='system'){const r=this.#rfq(rfqId);if(r.status!=='OPEN'||Date.now()>Date.parse(r.expiresAt))throw Error('RFQ_NOT_OPEN');if(r.invitedProviders.length&&!r.invitedProviders.includes(input.providerId))throw Error('PROVIDER_NOT_INVITED');const q={id:id(),providerId:input.providerId,priceMinor:pos(input.priceMinor,'PRICE'),quantity:pos(input.quantity,'QUANTITY'),validUntil:input.validUntil||r.expiresAt,venueId:input.venueId||null,createdAt:now(),createdBy:actor};r.quotes.push(q);return q}
 acceptRFQ(rfqId,quoteId,actor='system'){const r=this.#rfq(rfqId),q=r.quotes.find(x=>x.id===quoteId);if(!q)throw Error('RFQ_QUOTE_NOT_FOUND');if(r.status!=='OPEN'||Date.now()>Date.parse(q.validUntil))throw Error('RFQ_QUOTE_EXPIRED');const quantity=Math.min(r.quantity,q.quantity);if(quantity<r.minimumFill)throw Error('RFQ_MINIMUM_FILL_NOT_MET');const buyerId=r.side==='BUY'?r.requesterId:q.providerId,sellerId=r.side==='SELL'?r.requesterId:q.providerId;const gate=this.#gate({securityId:r.securityId,issuerId:this.capTable?.shareClass(r.securityId)?.issuerId,side:r.side,participantId:r.requesterId,counterpartyId:q.providerId,quantity,priceMinor:q.priceMinor});if(gate.decision!=='ALLOW')throw Error('PRE_TRADE_GATE_DENIED');const base={id:id(),securityId:r.securityId,issuerId:this.capTable?.shareClass(r.securityId)?.issuerId,buyOrderId:null,sellOrderId:null,buyerId,sellerId,quantity,priceMinor:q.priceMinor,currency:r.currency,status:'MATCHED_UNSETTLED',venueId:q.venueId||'RFQ',matchedAt:now(),rfqId:r.id,rfqQuoteId:q.id,integrityFlags:[]};const t={...base,tradeHash:hash(base)};this.trades.push(t);r.status='ACCEPTED';r.acceptedQuoteId=q.id;this.pricing?.observe({securityId:r.securityId,type:'TRADE',priceMinor:q.priceMinor,quantity,currency:r.currency,source:'GOX_RFQ',sourceRef:t.id},actor);this.#audit('LIQUIDITY_RFQ_ACCEPTED',actor,t.id,{rfqId:r.id,quantity,priceMinor:q.priceMinor});return t}
 alertsFor(securityId){return this.alerts.filter(a=>!securityId||a.securityId===securityId)}
 #gate(input){if(this.preTradeGate)return this.preTradeGate(input);if(!input.participantId)return{decision:'DENY',reasons:['PARTICIPANT_REQUIRED']};if(input.side==='SELL'&&this.capTable&&input.issuerId&&this.capTable.balance(input.issuerId,input.securityId,input.participantId)<input.quantity)return{decision:'DENY',reasons:['INSUFFICIENT_CAP_TABLE_BALANCE']};return{decision:'ALLOW',reasons:[],checkedAt:now(),components:['SECURITY','SELLER_BALANCE']}}
 #integrity(securityId,priceMinor,b,s){if(b.participantId===s.participantId)return{block:true,flags:['SELF_TRADE']};const m=this.pricing?.market(securityId)||{};const ref=m.referenceMinor??m.midMinor;if(!ref)return{block:false,flags:['NO_REFERENCE_PRICE']};const deviation=Math.abs(priceMinor-ref)/ref*10000;return{block:deviation>5000,flags:deviation>2500?['PRICE_DEVIATION']:[],deviationBps:Math.round(deviation)}}
 #executionPrice(b,s){if(b.type==='MARKET'&&s.type==='MARKET'){const m=this.pricing?.market(b.securityId);if(!m?.referenceMinor&&!m?.midMinor)throw Error('NO_MARKET_REFERENCE');return m.referenceMinor??m.midMinor}if(b.type==='MARKET')return s.priceMinor;if(s.type==='MARKET')return b.priceMinor;return Date.parse(b.createdAt)<Date.parse(s.createdAt)?b.priceMinor:s.priceMinor}
 #fill(o,q){o.remainingQuantity-=q;o.status=o.remainingQuantity===0?'FILLED':'PARTIALLY_FILLED';o.updatedAt=now()}
 #alert(securityId,type,details,actor){const a={id:id(),securityId,type,details,createdAt:now(),createdBy:actor};this.alerts.push(a);this.#audit('LIQUIDITY_ALERT_CREATED',actor,a.id,{securityId,type});return a}
 #security(s){if(!s)throw Error('SECURITY_REQUIRED');return this.capTable?.shareClass(s)} #order(i){const o=this.orders.get(i);if(!o)throw Error('ORDER_NOT_FOUND');return o} #rfq(i){const r=this.rfqs.get(i);if(!r)throw Error('RFQ_NOT_FOUND');return r} #audit(type,actor,subjectId,metadata){this.audit?.append({type,actor,subjectId,metadata})}
}
