import { randomUUID, createHash } from 'node:crypto';
const id=()=>randomUUID(), now=()=>new Date().toISOString();
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const positive=(x,name)=>{const v=Number(x);if(!Number.isFinite(v)||v<=0)throw Error(`INVALID_${name}`);return v};
export class PriceDiscoveryService{
 constructor({audit,capTable}={}){this.audit=audit;this.capTable=capTable;this.observations=[];this.quotes=[];this.auctions=new Map();this.alerts=[]}
 observe(input,actor='system'){
  this.#security(input.securityId);const priceMinor=positive(input.priceMinor,'PRICE');const observedAt=input.observedAt||now();
  const o={id:id(),securityId:input.securityId,type:input.type||'REFERENCE',side:input.side||null,priceMinor,quantity:input.quantity==null?null:positive(input.quantity,'QUANTITY'),currency:input.currency||this.#currency(input.securityId),source:input.source||'GOX',sourceRef:input.sourceRef||null,observedAt,expiresAt:input.expiresAt||null,confidence:Number(input.confidence??1),metadata:input.metadata||{},createdAt:now(),createdBy:actor};
  o.provenanceHash=hash({securityId:o.securityId,type:o.type,side:o.side,priceMinor:o.priceMinor,quantity:o.quantity,currency:o.currency,source:o.source,sourceRef:o.sourceRef,observedAt:o.observedAt});this.observations.push(o);this.#audit('PRICE_OBSERVATION_RECORDED',actor,o.id,{securityId:o.securityId,type:o.type,source:o.source,provenanceHash:o.provenanceHash});return o
 }
 market(securityId,{maxAgeMs=86_400_000,at=Date.now()}={}){this.#security(securityId);const active=this.observations.filter(o=>o.securityId===securityId&&Date.parse(o.observedAt)<=at&&(!o.expiresAt||Date.parse(o.expiresAt)>=at));const fresh=active.filter(o=>at-Date.parse(o.observedAt)<=maxAgeMs);const bids=fresh.filter(o=>o.side==='BUY'),asks=fresh.filter(o=>o.side==='SELL');const bestBid=bids.length?Math.max(...bids.map(x=>x.priceMinor)):null,bestAsk=asks.length?Math.min(...asks.map(x=>x.priceMinor)):null;const refs=fresh.filter(o=>['REFERENCE','TRADE','VALUATION','AUCTION_CLEAR'].includes(o.type));const referenceMinor=refs.length?Math.round(refs.reduce((s,x)=>s+x.priceMinor*Math.max(.01,x.confidence),0)/refs.reduce((s,x)=>s+Math.max(.01,x.confidence),0)):null;return{securityId,currency:this.#currency(securityId),bestBid,bestAsk,midMinor:bestBid!=null&&bestAsk!=null?Math.round((bestBid+bestAsk)/2):null,referenceMinor,observationCount:active.length,freshObservationCount:fresh.length,stale:active.length>0&&fresh.length===0,asOf:new Date(at).toISOString()}}
 quote(input,actor='system'){
  const m=this.market(input.securityId,{maxAgeMs:input.maxAgeMs??86_400_000});const side=input.side;if(!['BUY','SELL'].includes(side))throw Error('INVALID_SIDE');const priceMinor=side==='BUY'?m.bestAsk:m.bestBid;if(priceMinor==null)throw Error('NO_EXECUTABLE_MARKET');const q=positive(input.quantity,'QUANTITY');const band=this.#bandCheck(input.securityId,priceMinor,input.maxDeviationBps??2500);const status=band.review?'REVIEW':'EXECUTABLE';const quote={id:id(),securityId:input.securityId,side,quantity:q,priceMinor,currency:m.currency,status,validUntil:new Date(Date.now()+(input.ttlMs??30_000)).toISOString(),referenceMinor:band.referenceMinor,deviationBps:band.deviationBps,flags:band.flags,createdAt:now(),createdBy:actor};quote.quoteHash=hash(quote);this.quotes.push(quote);if(band.review)this.#alert(input.securityId,'PRICE_BAND_REVIEW',{quoteId:quote.id,...band},actor);this.#audit('PRICE_QUOTE_CREATED',actor,quote.id,{securityId:quote.securityId,status,priceMinor,quoteHash:quote.quoteHash});return quote
 }
 createAuction(input,actor='system'){this.#security(input.securityId);const a={id:id(),securityId:input.securityId,currency:input.currency||this.#currency(input.securityId),opensAt:input.opensAt||now(),closesAt:input.closesAt,minimumQuantity:Number(input.minimumQuantity||0),reservePriceMinor:input.reservePriceMinor==null?null:positive(input.reservePriceMinor,'RESERVE_PRICE'),status:'OPEN',orders:[],createdAt:now(),createdBy:actor};if(!a.closesAt||Date.parse(a.closesAt)<=Date.parse(a.opensAt))throw Error('INVALID_AUCTION_WINDOW');this.auctions.set(a.id,a);this.#audit('PRICE_AUCTION_CREATED',actor,a.id,{securityId:a.securityId});return a}
 submitAuctionOrder(auctionId,input,actor='system'){const a=this.#auction(auctionId);if(a.status!=='OPEN')throw Error('AUCTION_NOT_OPEN');if(Date.now()>Date.parse(a.closesAt))throw Error('AUCTION_CLOSED');if(!['BUY','SELL'].includes(input.side))throw Error('INVALID_SIDE');const o={id:id(),participantId:input.participantId,side:input.side,quantity:positive(input.quantity,'QUANTITY'),priceMinor:positive(input.priceMinor,'PRICE'),submittedAt:now(),createdBy:actor};a.orders.push(o);return o}
 clearAuction(auctionId,actor='system'){const a=this.#auction(auctionId);if(a.status!=='OPEN')throw Error('AUCTION_NOT_OPEN');const prices=[...new Set(a.orders.map(o=>o.priceMinor))].sort((x,y)=>x-y);let best=null;for(const p of prices){const demand=a.orders.filter(o=>o.side==='BUY'&&o.priceMinor>=p).reduce((s,o)=>s+o.quantity,0),supply=a.orders.filter(o=>o.side==='SELL'&&o.priceMinor<=p).reduce((s,o)=>s+o.quantity,0),volume=Math.min(demand,supply),imbalance=Math.abs(demand-supply);if(!best||volume>best.volume||(volume===best.volume&&imbalance<best.imbalance))best={priceMinor:p,volume,imbalance,demand,supply}}
  if(!best||best.volume<a.minimumQuantity||(a.reservePriceMinor!=null&&best.priceMinor<a.reservePriceMinor)){a.status='NO_CLEAR';a.clearedAt=now();a.result=best;return a}
  a.status='CLEARED';a.clearedAt=now();a.result=best;this.observe({securityId:a.securityId,type:'AUCTION_CLEAR',priceMinor:best.priceMinor,quantity:best.volume,currency:a.currency,source:'GOX_AUCTION',sourceRef:a.id},actor);this.#audit('PRICE_AUCTION_CLEARED',actor,a.id,{securityId:a.securityId,...best});return a
 }
 history(securityId,{limit=100}={}){this.#security(securityId);return this.observations.filter(o=>o.securityId===securityId).sort((a,b)=>Date.parse(b.observedAt)-Date.parse(a.observedAt)).slice(0,limit)}
 alertsFor(securityId){return this.alerts.filter(a=>a.securityId===securityId)}
 #bandCheck(securityId,priceMinor,maxDeviationBps){const m=this.market(securityId);const ref=m.referenceMinor??m.midMinor;if(ref==null)return{referenceMinor:null,deviationBps:null,review:true,flags:['NO_REFERENCE_PRICE']};const deviationBps=Math.round(Math.abs(priceMinor-ref)/ref*10000);return{referenceMinor:ref,deviationBps,review:deviationBps>maxDeviationBps,flags:deviationBps>maxDeviationBps?['PRICE_OUTSIDE_BAND']:[]}}
 #alert(securityId,type,details,actor){const a={id:id(),securityId,type,details,createdAt:now(),createdBy:actor};this.alerts.push(a);this.#audit('PRICE_ALERT_CREATED',actor,a.id,{securityId,type});return a}
 #security(securityId){if(!securityId)throw Error('SECURITY_REQUIRED');return this.capTable?.shareClass(securityId)} #currency(securityId){return this.capTable?.shareClass(securityId)?.currency||'USD'} #auction(i){const a=this.auctions.get(i);if(!a)throw Error('AUCTION_NOT_FOUND');return a} #audit(type,actor,subjectId,metadata){this.audit?.append({type,actor,subjectId,metadata})}
}
