import { randomUUID, createHash } from 'node:crypto';
const id=()=>randomUUID(), now=()=>new Date().toISOString();
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
export class MemorySettlementAdapter{
 constructor(kind='GENERIC'){this.kind=kind;this.reservations=new Map();this.completions=new Map()}
 reserve(input){const key=input.idempotencyKey;if(this.reservations.has(key))return this.reservations.get(key);const r={id:id(),kind:this.kind,status:'RESERVED',externalRef:`${this.kind}-${id()}`,reservedAt:now(),...input};this.reservations.set(key,r);return r}
 complete(input){const key=input.idempotencyKey;if(this.completions.has(key))return this.completions.get(key);const r={id:id(),kind:this.kind,status:'COMPLETED',externalRef:`${this.kind}-${id()}`,completedAt:now(),...input};this.completions.set(key,r);return r}
 release(input){const r=this.reservations.get(input.idempotencyKey);if(r)r.status='RELEASED';return r||null}
 reconcile(input){return {status:'CONFIRMED',externalRef:input.externalRef||null,checkedAt:now()}}
}
export class SettlementService{
 constructor({audit,liquidity,capTable,cashAdapter,securitiesAdapter}={}){this.audit=audit;this.liquidity=liquidity;this.capTable=capTable;this.cash=cashAdapter||new MemorySettlementAdapter('CASH');this.securities=securitiesAdapter||new MemorySettlementAdapter('SECURITIES');this.records=new Map();this.byTrade=new Map();this.receipts=[]}
 createFromTrade(tradeId,input={},actor='system'){if(this.byTrade.has(tradeId))return this.get(this.byTrade.get(tradeId));const t=this.liquidity?.trade(tradeId);if(!t)throw Error('TRADE_NOT_FOUND');if(t.status!=='MATCHED_UNSETTLED')throw Error('TRADE_NOT_SETTLEABLE');const c=this.capTable.shareClass(t.securityId);const base={id:id(),tradeId:t.id,tradeHash:t.tradeHash,issuerId:t.issuerId||c.issuerId,securityId:t.securityId,buyerId:t.buyerId,sellerId:t.sellerId,quantity:t.quantity,priceMinor:t.priceMinor,currency:t.currency||c.currency,cashAmountMinor:t.quantity*t.priceMinor,status:'INSTRUCTED',cashStatus:'PENDING',securitiesStatus:'PENDING',cashReservation:null,securitiesReservation:null,capTableEntryId:null,failureReason:null,createdAt:now(),updatedAt:now(),createdBy:actor,timeoutAt:input.timeoutAt||new Date(Date.now()+(input.timeoutMs||86400000)).toISOString(),programDecision:input.programDecision||{id:`settlement-${t.id}`,decision:'ALLOW'}};const s={...base,instructionHash:hash(base)};this.records.set(s.id,s);this.byTrade.set(t.id,s.id);this.#audit('SETTLEMENT_INSTRUCTED',actor,s.id,{tradeId:t.id,instructionHash:s.instructionHash});return s}
 // legacy/dev compatibility only; production flows should create from a matched trade.
 create(tradeId){if(this.byTrade.has(tradeId))return this.get(this.byTrade.get(tradeId));const s={id:id(),tradeId,status:'PENDING',cashStatus:'PENDING',securitiesStatus:'PENDING',assetStatus:'PENDING',legacy:true,createdAt:now(),updatedAt:now()};this.records.set(s.id,s);this.byTrade.set(tradeId,s.id);return s}
 reserve(settlementId,actor='settlement-engine'){const s=this.get(settlementId);this.#ensureNotFinal(s);if(s.legacy)throw Error('LEGACY_SETTLEMENT_CANNOT_RESERVE');try{if(s.cashStatus==='PENDING'){s.cashReservation=this.cash.reserve({idempotencyKey:`${s.id}:cash:reserve`,settlementId:s.id,tradeId:s.tradeId,payerId:s.buyerId,payeeId:s.sellerId,amountMinor:s.cashAmountMinor,currency:s.currency});s.cashStatus='RESERVED'}if(s.securitiesStatus==='PENDING'){s.securitiesReservation=this.securities.reserve({idempotencyKey:`${s.id}:securities:reserve`,settlementId:s.id,tradeId:s.tradeId,issuerId:s.issuerId,securityId:s.securityId,fromOwnerId:s.sellerId,toOwnerId:s.buyerId,quantity:s.quantity});s.securitiesStatus='RESERVED'}s.status='RESERVED';s.updatedAt=now();this.#audit('SETTLEMENT_RESERVED',actor,s.id,{cashStatus:s.cashStatus,securitiesStatus:s.securitiesStatus});return s}catch(e){s.status='FAILED';s.failureReason=e.message;s.updatedAt=now();this.#release(s);throw e}}
 settle(settlementId,actor='settlement-engine'){const s=this.get(settlementId);if(s.status==='SETTLED')return s;if(s.legacy)throw Error('LEGACY_SETTLEMENT_CANNOT_DVP');if(Date.now()>Date.parse(s.timeoutAt)){s.status='RECONCILIATION_REQUIRED';s.failureReason='SETTLEMENT_TIMEOUT';s.updatedAt=now();return s}if(s.status==='INSTRUCTED')this.reserve(s.id,actor);if(s.status!=='RESERVED'&&s.status!=='PROCESSING')throw Error('SETTLEMENT_NOT_RESERVED');s.status='PROCESSING';try{if(s.cashStatus!=='COMPLETED'){s.cashCompletion=this.cash.complete({idempotencyKey:`${s.id}:cash:complete`,settlementId:s.id,reservationRef:s.cashReservation.externalRef,amountMinor:s.cashAmountMinor,currency:s.currency});s.cashStatus=s.cashCompletion.status==='COMPLETED'?'COMPLETED':'UNKNOWN'}if(s.securitiesStatus!=='COMPLETED'){s.securitiesCompletion=this.securities.complete({idempotencyKey:`${s.id}:securities:complete`,settlementId:s.id,reservationRef:s.securitiesReservation.externalRef,securityId:s.securityId,quantity:s.quantity});s.securitiesStatus=s.securitiesCompletion.status==='COMPLETED'?'COMPLETED':'UNKNOWN'}if(s.cashStatus!=='COMPLETED'||s.securitiesStatus!=='COMPLETED'){s.status='RECONCILIATION_REQUIRED';s.updatedAt=now();return s}if(!s.capTableEntryId){const e=this.capTable.transfer({issuerId:s.issuerId,securityId:s.securityId,fromOwnerId:s.sellerId,toOwnerId:s.buyerId,quantity:s.quantity,reference:`settlement:${s.id}`,programDecision:s.programDecision},actor);s.capTableEntryId=e.id}const t=this.liquidity?.trade(s.tradeId);if(t)t.status='SETTLED';s.status='SETTLED';s.updatedAt=now();const receiptBase={id:id(),settlementId:s.id,tradeId:s.tradeId,instructionHash:s.instructionHash,cashExternalRef:s.cashCompletion.externalRef,securitiesExternalRef:s.securitiesCompletion.externalRef,capTableEntryId:s.capTableEntryId,settledAt:now()};const receipt={...receiptBase,receiptHash:hash(receiptBase)};this.receipts.push(receipt);s.receiptId=receipt.id;this.#audit('SETTLEMENT_COMPLETED',actor,s.id,{tradeId:s.tradeId,receiptHash:receipt.receiptHash,capTableEntryId:s.capTableEntryId});return s}catch(e){s.status='RECONCILIATION_REQUIRED';s.failureReason=e.message;s.updatedAt=now();this.#audit('SETTLEMENT_RECONCILIATION_REQUIRED',actor,s.id,{reason:e.message});return s}}
 confirm(settlementId,leg){const s=this.get(settlementId);if(!s.legacy)throw Error('USE_DVP_SETTLE');if(leg==='cash')s.cashStatus='CONFIRMED';else{s.securitiesStatus='CONFIRMED';s.assetStatus='CONFIRMED'}if(s.cashStatus==='CONFIRMED'&&s.securitiesStatus==='CONFIRMED')s.status='SETTLED';s.updatedAt=now();return s}
 reconcile(settlementId,actor='system'){const s=this.get(settlementId);if(s.legacy)return s;const cash=this.cash.reconcile({externalRef:s.cashCompletion?.externalRef||s.cashReservation?.externalRef}),securities=this.securities.reconcile({externalRef:s.securitiesCompletion?.externalRef||s.securitiesReservation?.externalRef});const r={settlementId:s.id,cash,securities,checkedAt:now()};if(cash.status==='CONFIRMED'&&securities.status==='CONFIRMED'&&s.status!=='SETTLED')return this.settle(s.id,actor);this.#audit('SETTLEMENT_RECONCILED',actor,s.id,r);return {...s,reconciliation:r}}
 get(i){const s=this.records.get(i);if(!s)throw Error('SETTLEMENT_NOT_FOUND');return s}
 receipt(i){const r=this.receipts.find(x=>x.id===i||x.settlementId===i);if(!r)throw Error('SETTLEMENT_RECEIPT_NOT_FOUND');return r}
 list(){return [...this.records.values()]}
 #ensureNotFinal(s){if(['SETTLED','CANCELED'].includes(s.status))throw Error('SETTLEMENT_FINAL')}
 #release(s){try{if(s.cashReservation)this.cash.release({idempotencyKey:`${s.id}:cash:reserve`});if(s.securitiesReservation)this.securities.release({idempotencyKey:`${s.id}:securities:reserve`})}catch{}}
 #audit(type,actor,subjectId,metadata){this.audit?.append({type,actor,subjectId,metadata})}
}
