import ExcelJS from "exceljs";
import {readFileSync} from "node:fs";
import {join} from "node:path";
import {describe,expect,it} from "vitest";
import {parseBankOrPayout,parseInvoices} from "../../src/server/parsers";
import {runMatch} from "../../src/server/matching/engine";
import {JOURNAL_COLUMNS,journalCsv,journalRows,workpaperRows,workpaperXlsx,type ExportData} from "../../src/server/api/exports";

const fixture=(name:string)=>readFileSync(join(process.cwd(),"tests","fixtures",name));
function exportFixture():{data:ExportData;result:ReturnType<typeof runMatch>}{const invoices=parseInvoices(fixture("invoices.csv"),"invoices.csv").rows,txns=parseBankOrPayout(fixture("payouts.csv"),"payouts.csv").rows,result=runMatch(invoices,txns,{}),invoiceMap=new Map(invoices.map((invoice,index)=>[invoice.invoiceNumber,{...invoice,id:`invoice-${index}`,amountMinor:invoice.amountMinor,dueDate:new Date(`${invoice.dueDate}T00:00:00Z`)}])),txnMap=new Map(txns.map((txn,index)=>[txn.vendorId??txn.fingerprint,{...txn,id:`txn-${index}`,vendorId:txn.vendorId??null,postedAt:new Date(`${txn.postedAt}T00:00:00Z`),valueDate:txn.valueDate?new Date(`${txn.valueDate}T00:00:00Z`):null}]));const links=result.links.map((link,index)=>({...link,id:`link-${index}`,status:"PROPOSED",expectedMinor:BigInt(link.expectedMinor),receivedMinor:BigInt(link.receivedMinor),feeMinor:BigInt(link.feeMinor),fxDiffMinor:BigInt(link.fxDiffMinor),invoice:invoiceMap.get(link.invoiceNumber)!,txn:txnMap.get(link.txnId)!}));return{result,data:{runId:"golden-run",createdAt:new Date("2025-04-01T00:00:00Z"),settings:{},links,unmatchedInvoices:result.unmatchedInvoices.map(invoice=>invoiceMap.get(invoice.invoiceNumber)!),unallocatedIn:result.unallocated_in.map(txn=>txnMap.get(txn.vendorId??txn.fingerprint)!),unallocatedOut:result.unallocated_out.map(txn=>txnMap.get(txn.vendorId??txn.fingerprint)!),audit:[{createdAt:new Date("2025-04-01T00:00:00Z"),action:"RUN",userId:"user-1",payload:{runId:"golden-run"}}]}};}
const sum=(values:bigint[])=>values.reduce((total,value)=>total+value,0n);

describe("Task 7 exports",()=>{
  it("conserves engine amount_minor totals in every workpaper bucket",()=>{const{data,result}=exportFixture(),rows=workpaperRows(data),totals={matched:sum(result.links.filter(link=>link.bucket==="matched").map(link=>BigInt(link.receivedMinor))),short_payment:sum(result.links.filter(link=>link.bucket==="short_payment").map(link=>BigInt(link.receivedMinor))),fx_gap:sum(result.links.filter(link=>link.bucket==="fx_gap").map(link=>BigInt(link.receivedMinor))),unallocated_in:sum(result.unallocated_in.map(txn=>txn.amountMinor)),unallocated_out:sum(result.unallocated_out.map(txn=>txn.amountMinor))};for(const[bucket,total]of Object.entries(totals))expect(sum(rows.filter(row=>row.bucket===bucket).map(row=>row.amountMinor)),bucket).toBe(total);});
  it("creates the seven locked workbook sheets with fixture row counts",async()=>{const{data}=exportFixture(),buffer=await workpaperXlsx(data),workbook=new ExcelJS.Workbook();await workbook.xlsx.load(buffer);expect(workbook.worksheets.map(sheet=>sheet.name)).toEqual(["Summary","Matched","Short payments","FX gaps","Unallocated incoming","Unallocated outgoing","Audit"]);expect(workbook.getWorksheet("Matched")!.rowCount-1).toBe(5);expect(workbook.getWorksheet("Short payments")!.rowCount-1).toBe(2);expect(workbook.getWorksheet("FX gaps")!.rowCount-1).toBe(0);expect(workbook.getWorksheet("Unallocated incoming")!.rowCount-1).toBe(6);expect(workbook.getWorksheet("Unallocated outgoing")!.rowCount-1).toBe(2);expect(workbook.getWorksheet("Short payments")?.getRow(1).values).toEqual(expect.arrayContaining(["Difference minor","Suggested fee account label"]));expect(workbook.getWorksheet("Audit")?.getRow(1).values).toContain("Settings JSON");});
  it("writes exact journal columns, split labels, and reconciled bucket totals",()=>{const{data,result}=exportFixture(),csv=journalCsv(data),rows=journalRows(data);expect(csv.split("\r\n")[0]).toBe(JOURNAL_COLUMNS.join(","));expect(rows.filter(row=>row.invoice_number==="INV-1002").map(row=>[row.debit_account,row.credit_account,row.class])).toEqual([["Bank","AR","short_payment"],["Bank fee","AR","short_payment"]]);expect(rows.filter(row=>row.invoice_number==="INV-1010").map(row=>[row.debit_account,row.credit_account,row.class])).toEqual([["Bank","AR","matched"],["Bank","Unapplied overpayment","matched"]]);expect(rows.find(row=>row.txn_id==="TXN-11")).toMatchObject({debit_account:"Unallocated",credit_account:"Bank",class:"unallocated_out"});const journalTotals=Object.fromEntries(["matched","short_payment","unallocated_in","unallocated_out"].map(bucket=>[bucket,sum(rows.filter(row=>row.class===bucket).map(row=>BigInt(row.amount_minor)))]));expect(journalTotals.matched).toBe(sum(result.links.filter(link=>link.bucket==="matched").map(link=>BigInt(link.receivedMinor))));expect(journalTotals.short_payment).toBe(sum(result.links.filter(link=>link.bucket==="short_payment").map(link=>BigInt(link.expectedMinor))));expect(journalTotals.unallocated_in).toBe(sum(result.unallocated_in.map(txn=>txn.amountMinor)));expect(journalTotals.unallocated_out).toBe(sum(result.unallocated_out.map(txn=>txn.amountMinor<0n?-txn.amountMinor:txn.amountMinor)));});
});
