import {readFileSync} from "node:fs";
import {join} from "node:path";
import {describe,expect,it} from "vitest";
import {parseBankOrPayout,parseInvoices} from "../../src/server/parsers";
import {runMatch} from "../../src/server/matching/engine";
const fixture=(name:string)=>readFileSync(join(process.cwd(),"tests","fixtures",name));
const load=()=>{const invoices=parseInvoices(fixture("invoices.csv"),"invoices.csv"),txns=parseBankOrPayout(fixture("payouts.csv"),"payouts.csv");expect(invoices.errors).toEqual([]);expect(txns.errors).toEqual([]);return{invoices:invoices.rows,txns:txns.rows};};
describe("Task 4 golden matcher",()=>{it("matches the locked golden result",()=>{const {invoices,txns}=load(),golden=JSON.parse(fixture("expected_match.json").toString("utf8")),result=runMatch(invoices,txns,golden.settings);expect(result.links).toHaveLength(golden.links.length);for(const expected of golden.links){const actual=result.links.find(link=>link.invoiceNumber===expected.invoiceNumber&&link.txnId===expected.txnId);expect(actual).toBeDefined();expect(actual).toMatchObject({invoiceNumber:expected.invoiceNumber,txnId:expected.txnId,bucket:expected.bucket,method:expected.method,flags:expected.flags,expectedMinor:expected.expectedMinor,receivedMinor:expected.receivedMinor,feeMinor:expected.feeMinor,fxDiffMinor:expected.fxDiffMinor});expect(actual!.confidence).toBeGreaterThanOrEqual(expected.minConfidence)}expect(result.unmatchedInvoices.map(x=>x.invoiceNumber)).toEqual(golden.unmatchedInvoices);expect(result.unallocated_in.map(x=>x.vendorId)).toEqual(golden.unallocated_in);expect(result.unallocated_out.map(x=>x.vendorId)).toEqual(golden.unallocated_out);expect(result.suggestions.map(suggestion=>({type:suggestion.type,...suggestion.invoiceNumber?{invoiceNumber:suggestion.invoiceNumber}:{},txnId:suggestion.txnId,...suggestion.invoiceNumbers?{invoiceNumbers:suggestion.invoiceNumbers}:{},reason:suggestion.reason}))).toEqual(golden.suggestions)})});
describe("Task 4 mandatory extras",()=>{it("gives TXN-01 the exact-ref win and leaves TXN-14 unlinked",()=>{const {invoices,txns}=load(),result=runMatch(invoices,txns,{});expect(result.links.find(x=>x.invoiceNumber==="INV-1001")?.txnId).toBe("TXN-01");expect(result.links.some(x=>x.txnId==="TXN-14")).toBe(false)});it("keeps TXN-05 as a suggestion for remaining INV-1005",()=>{const {invoices,txns}=load(),result=runMatch(invoices,txns,{});expect(result.links.some(x=>x.txnId==="TXN-05")).toBe(false);expect(result.suggestions).toContainEqual(expect.objectContaining({type:"AMOUNT_DATE",invoiceNumber:"INV-1005",txnId:"TXN-05"}))});it("links late ORPH-1 only with a 120-day after-window",()=>{const {invoices,txns}=load();expect(runMatch(invoices,txns,{}).links.some(x=>x.invoiceNumber==="INV-1012")).toBe(false);expect(runMatch(invoices,txns,{dateWindowDaysAfter:120}).links).toContainEqual(expect.objectContaining({invoiceNumber:"INV-1012",txnId:"TXN-15"}))});it("never links outbound TXN-11",()=>{const {invoices,txns}=load(),result=runMatch(invoices,txns,{});expect(result.links.some(x=>x.txnId==="TXN-11")).toBe(false);expect(result.unallocated_out.map(x=>x.vendorId)).toContain("TXN-11")});it("handles empty inputs",()=>expect(runMatch([],[],{})).toEqual({links:[],unmatchedInvoices:[],unallocated_in:[],unallocated_out:[],suggestions:[]}));it("never hard-links TXN-08 to two invoices",()=>{const {invoices,txns}=load(),result=runMatch(invoices,txns,{});expect(result.links.some(x=>x.txnId==="TXN-08")).toBe(false)});it("writes a non-empty sentence for every link",()=>{const {invoices,txns}=load();for(const link of runMatch(invoices,txns,{}).links){expect(link.explanation.trim()).not.toBe("");expect(link.explanation).toMatch(/[.!?]$/)}})});
