import {useState} from 'react';
import {createJob,runJob,DISCLAIMER} from '../api';
import {previewCsv} from '../csv';
export default function Upload({jobId,onCreated,onRun}:{jobId:string;onCreated:(id:string)=>void;onRun:()=>void}){
 const [bank,setBank]=useState<File>();const [gl,setGl]=useState<File>();const [previews,setPreviews]=useState<Record<string,string[][]>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function file(kind:string,f?:File){if(kind==='bank')setBank(f);else setGl(f);setPreviews(p=>({...p,[kind]:[]}));if(f){const rows=previewCsv(await f.text());setPreviews(p=>({...p,[kind]:rows}));}}
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!bank||!gl)return;setBusy(true);setError('');const form=new FormData(e.currentTarget);const optional=(key:string)=>{const raw=String(form.get(key)||'');if(!raw)return null;const n=Number(raw);if(!Number.isSafeInteger(n))throw Error(key+' must be integer cents');return n};try{const config={entity_name:form.get('entity_name'),currency:form.get('currency'),cash_account_ids:String(form.get('cash_account_ids')).split(',').map(s=>s.trim()).filter(Boolean),period_start:form.get('period_start'),period_end:form.get('period_end'),period_close_date:form.get('period_close_date')||null,expected_opening_cash_cents:optional('expected_opening_cash_cents'),expected_closing_cash_cents:optional('expected_closing_cash_cents'),expected_bank_statement_ending_cents:optional('expected_bank_statement_ending_cents'),export_dialect:form.get('export_dialect'),license_key:form.get('license_key')};const r=await createJob(bank,gl,config);onCreated(r.job_id)}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function run(){setBusy(true);setError('');try{await runJob(jobId);onRun()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <section><p className="eyebrow">01 / IMPORT</p><h1>Start with the source books.</h1><p className="sub">Upload local exports. Reconstruct the period. Review every exception.</p><p className="notice">{DISCLAIMER}</p><form onSubmit={create}><fieldset disabled={busy}><div className="form-grid">{[['entity_name','Entity name','text','Acme LLC'],['currency','Currency','text','USD'],['cash_account_ids','Cash account IDs','text','1000'],['period_start','Period start','date','2025-01-01'],['period_end','Period end','date','2025-12-31'],['period_close_date','Close date (optional)','date','2026-01-15'],['expected_opening_cash_cents','Opening cash (integer cents)','number','100000'],['expected_closing_cash_cents','Closing cash (optional cents)','number',''],['expected_bank_statement_ending_cents','Bank statement ending (cents)','number',''],['license_key','License Key (Required)','password','test_stripe_key']].map(([name,label,type,value])=><label key={name}>{label} {name==='license_key'&&<small>(Purchase <a href="https://buy.stripe.com/test_aFadR16mT8qxd3HcWzcjS02" target="_blank" rel="noreferrer">Solo</a> or <a href="https://buy.stripe.com/test_bJebIT7qX5el3t7cWzcjS01" target="_blank" rel="noreferrer">Firm</a> license)</small>}<input name={name} type={type} defaultValue={value} step={type==='number'?'1':undefined} required={!name.includes('expected_')&&name!=='period_close_date'}/></label>)}<label>Export dialect<select name="export_dialect" defaultValue="generic"><option value="generic">Generic</option><option value="qbo">QBO CSV</option><option value="xero">Xero CSV</option></select></label></div><div className="uploads">{['bank','gl'].map(kind=><label className="file" key={kind}>{kind==='bank'?'Bank CSV':'GL CSV'}<input type="file" accept=".csv" required onChange={e=>void file(kind,e.target.files?.[0])}/></label>)}</div><button type="submit">Create job</button></fieldset></form>{jobId&&<p className="job">Job {jobId} · ingested</p>}<button className="secondary" disabled={!jobId||busy} onClick={run}>{busy?'Working…':'Run AI Matching & Detectors'}</button>{error&&<pre role="alert">{error}</pre>}{Object.entries(previews).map(([kind,rows])=>rows?.length>0&&<div className="preview" key={kind}><h2>{kind.toUpperCase()} preview</h2><div className="scroll"><table><thead><tr>{rows[0].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.slice(1).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div></div>)}</section>
}
