import ExcelJS from "exceljs";
import type {ApiContext} from "./context";
import {ApiError} from "./context";
import {CURRENCY_EXPONENTS} from "../parsers/money";
import {resolveAccountLabels,type AccountLabels} from "../account-labels";
export type ExportInvoice={id:string;invoiceNumber:string;customerName:string;currency:string;amountMinor:bigint;dueDate:Date;rawJson:unknown};
export type ExportTxn={id:string;vendorId:string|null;postedAt:Date;valueDate:Date|null;currency:string;amountMinor:bigint;description:string;rawJson:unknown};
export type ExportLink={id:string;status:string;confidence:number;method:string;flags:string[];expectedMinor:bigint;receivedMinor:bigint;feeMinor:bigint;fxDiffMinor:bigint;explanation:string;invoice:ExportInvoice;txn:ExportTxn};
export type ExportAudit={createdAt:Date;action:string;userId:string|null;payload:unknown};
export type ExportData={runId:string;createdAt:Date;settings:unknown;accountLabels?:Partial<AccountLabels>;links:ExportLink[];unmatchedInvoices:ExportInvoice[];unallocatedIn:ExportTxn[];unallocatedOut:ExportTxn[];audit:ExportAudit[]};
export type WorkpaperBucket="matched"|"short_payment"|"fx_gap"|"unallocated_in"|"unallocated_out";
export type WorkpaperRow={bucket:WorkpaperBucket;invoiceNumber:string;customer:string;currency:string;expectedMinor:bigint;receivedMinor:bigint;amountMinor:bigint;txnDate:string;txnId:string;method:string;confidence:number|string;flags:string;explanation:string;description:string};
export const JOURNAL_COLUMNS=["date","currency","debit_account","credit_account","amount_minor","amount_major","memo","invoice_number","txn_id","class"] as const;
export type JournalRow=Record<(typeof JOURNAL_COLUMNS)[number],string>;
const dateOnly=(date:Date)=>date.toISOString().slice(0,10),txnDate=(txn:ExportTxn)=>dateOnly(txn.valueDate??txn.postedAt),txnId=(txn:ExportTxn)=>txn.vendorId??txn.id,absolute=(value:bigint)=>value<0n?-value:value;
export function amountMajor(minor:bigint,currency:string){const exponent=CURRENCY_EXPONENTS[currency as keyof typeof CURRENCY_EXPONENTS];if(exponent===undefined)throw new Error(`Unsupported currency ${currency}`);const sign=minor<0n?"-":"",digits=absolute(minor).toString();if(exponent===0)return`${sign}${digits}`;const padded=digits.padStart(exponent+1,"0");return`${sign}${padded.slice(0,-exponent)}.${padded.slice(-exponent)}`;}
export function linkBucket(link:ExportLink):Exclude<WorkpaperBucket,"unallocated_in"|"unallocated_out">{if(link.invoice.currency!==link.txn.currency||link.flags.includes("FX_GAP"))return"fx_gap";if(link.flags.includes("SHORT"))return"short_payment";return"matched";}
export function workpaperRows(data:ExportData):WorkpaperRow[]{const linked=data.links.filter(link=>link.status!=="REJECTED").map(link=>({bucket:linkBucket(link),invoiceNumber:link.invoice.invoiceNumber,customer:link.invoice.customerName,currency:link.txn.currency,expectedMinor:link.expectedMinor,receivedMinor:link.receivedMinor,amountMinor:link.receivedMinor,txnDate:txnDate(link.txn),txnId:txnId(link.txn),method:link.method,confidence:link.confidence,flags:link.flags.join(", "),explanation:link.explanation,description:link.txn.description}));const unallocated=(bucket:"unallocated_in"|"unallocated_out",txns:ExportTxn[])=>txns.map(txn=>({bucket,invoiceNumber:"",customer:"",currency:txn.currency,expectedMinor:0n,receivedMinor:txn.amountMinor,amountMinor:txn.amountMinor,txnDate:txnDate(txn),txnId:txnId(txn),method:"",confidence:"",flags:"",explanation:`${bucket==="unallocated_in"?"Inbound":"Outbound"} transaction has no auto link.`,description:txn.description}));return[...linked,...unallocated("unallocated_in",data.unallocatedIn),...unallocated("unallocated_out",data.unallocatedOut)];}
function journal(row:Omit<JournalRow,"amount_major">):JournalRow{return{...row,amount_major:amountMajor(BigInt(row.amount_minor),row.currency)};}
function linkedJournals(link:ExportLink,labels:AccountLabels):JournalRow[]{const base={date:txnDate(link.txn),currency:link.txn.currency,invoice_number:link.invoice.invoiceNumber,txn_id:txnId(link.txn)},memo=`${link.invoice.invoiceNumber}: ${link.explanation}`,difference=link.expectedMinor-link.receivedMinor,bucket=linkBucket(link);if(bucket==="fx_gap"){const value=link.fxDiffMinor;return value===0n?[]:[journal({...base,debit_account:value>0n?labels.fxGainLoss:labels.bank,credit_account:value>0n?labels.ar:labels.fxGainLoss,amount_minor:absolute(value).toString(),memo,class:"fx_gap"})];}if(link.flags.includes("OVER")){const residual=link.receivedMinor-link.expectedMinor;return[journal({...base,debit_account:labels.bank,credit_account:labels.ar,amount_minor:link.expectedMinor.toString(),memo,class:"matched"}),journal({...base,debit_account:labels.bank,credit_account:labels.unapplied,amount_minor:residual.toString(),memo:`${link.invoice.invoiceNumber}: overpayment residual`,class:"matched"})];}if(bucket==="short_payment"){const received=journal({...base,debit_account:labels.bank,credit_account:labels.ar,amount_minor:link.receivedMinor.toString(),memo,class:"short_payment"});if(link.flags.includes("FEE"))return[received,journal({...base,debit_account:labels.bankFee,credit_account:labels.ar,amount_minor:difference.toString(),memo:`${link.invoice.invoiceNumber}: fee difference`,class:"short_payment"})];return[received,journal({...base,debit_account:labels.shortRemainder,credit_account:labels.ar,amount_minor:difference.toString(),memo:`${link.invoice.invoiceNumber}: short remainder; review required`,class:"short_payment"})];}return[journal({...base,debit_account:labels.bank,credit_account:labels.ar,amount_minor:link.receivedMinor.toString(),memo,class:"matched"})];}
export function journalRows(data:ExportData):JournalRow[]{const labels=resolveAccountLabels(data.accountLabels),links=data.links.filter(link=>link.status!=="REJECTED").flatMap(link=>linkedJournals(link,labels)),incoming=data.unallocatedIn.map(txn=>journal({date:txnDate(txn),currency:txn.currency,debit_account:labels.bank,credit_account:labels.unallocated,amount_minor:txn.amountMinor.toString(),memo:txn.description,invoice_number:"",txn_id:txnId(txn),class:"unallocated_in"})),outgoing=data.unallocatedOut.map(txn=>journal({date:txnDate(txn),currency:txn.currency,debit_account:labels.unallocated,credit_account:labels.bank,amount_minor:absolute(txn.amountMinor).toString(),memo:txn.description,invoice_number:"",txn_id:txnId(txn),class:"unallocated_out"}));return[...links,...incoming,...outgoing];}
const csvCell=(value:string)=>/[",\r\n]/.test(value)?`"${value.replace(/"/g,'""')}"`:value;
export function journalCsv(data:ExportData){return[JOURNAL_COLUMNS.join(","),...journalRows(data).map(row=>JOURNAL_COLUMNS.map(column=>csvCell(row[column])).join(","))].join("\r\n")+"\r\n";}
const columns=[{header:"Invoice",key:"invoiceNumber",width:18},{header:"Customer",key:"customer",width:24},{header:"Currency",key:"currency",width:10},{header:"Expected minor",key:"expectedMinor",width:16},{header:"Received minor",key:"receivedMinor",width:16},{header:"Amount minor",key:"amountMinor",width:16},{header:"Txn date",key:"txnDate",width:13},{header:"Txn ID",key:"txnId",width:16},{header:"Method",key:"method",width:15},{header:"Confidence",key:"confidence",width:12},{header:"Flags",key:"flags",width:18},{header:"Why",key:"explanation",width:55},{header:"Description",key:"description",width:42}];
function styleSheet(sheet:ExcelJS.Worksheet){sheet.views=[{state:"frozen",ySplit:1}];sheet.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,sheet.rowCount),column:sheet.columnCount}};sheet.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF176B4D"}};sheet.eachRow(row=>{row.alignment={vertical:"top",wrapText:true}});}
export async function workpaperXlsx(data:ExportData){const labels=resolveAccountLabels(data.accountLabels),workbook=new ExcelJS.Workbook();workbook.creator="BorderBooks Matcher";workbook.created=data.createdAt;const rows=workpaperRows(data),summary=workbook.addWorksheet("Summary");summary.columns=[{header:"Bucket",key:"bucket",width:24},{header:"Currency",key:"currency",width:12},{header:"Count",key:"count",width:12},{header:"Amount minor",key:"amountMinor",width:18},{header:"Amount major",key:"amountMajor",width:18}];const summaryGroups=new Map<string,{bucket:string;currency:string;count:number;amount:bigint}>();for(const row of rows){const key=`${row.bucket}|${row.currency}`,current=summaryGroups.get(key)??{bucket:row.bucket,currency:row.currency,count:0,amount:0n};current.count++;current.amount+=absolute(row.amountMinor);summaryGroups.set(key,current);}summary.addRows([...summaryGroups.values()].map(group=>({bucket:group.bucket,currency:group.currency,count:group.count,amountMinor:group.amount.toString(),amountMajor:amountMajor(group.amount,group.currency)})));summary.addRow({bucket:"Unmatched invoices",currency:"",count:data.unmatchedInvoices.length,amountMinor:"",amountMajor:""});summary.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};summary.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF17211D"}};const names:[string,WorkpaperBucket][]=[["Matched","matched"],["Short payments","short_payment"],["FX gaps","fx_gap"],["Unallocated incoming","unallocated_in"],["Unallocated outgoing","unallocated_out"]];for(const[name,bucket]of names){const sheet=workbook.addWorksheet(name);sheet.columns=bucket==="short_payment"?[...columns,{header:"Difference minor",key:"differenceMinor",width:18},{header:"Suggested fee account label",key:"feeAccountLabel",width:28}]:columns;sheet.addRows(rows.filter(row=>row.bucket===bucket).map(row=>({...row,expectedMinor:row.expectedMinor.toString(),receivedMinor:row.receivedMinor.toString(),amountMinor:row.amountMinor.toString(),differenceMinor:(row.expectedMinor-row.receivedMinor).toString(),feeAccountLabel:row.flags.includes("FEE")?labels.bankFee:labels.shortRemainder})));styleSheet(sheet);}const audit=workbook.addWorksheet("Audit");audit.columns=[{header:"Timestamp UTC",key:"createdAt",width:24},{header:"Action",key:"action",width:14},{header:"User ID",key:"userId",width:24},{header:"Settings JSON",key:"settings",width:42},{header:"Payload",key:"payload",width:70}];audit.addRows(data.audit.map(event=>({createdAt:event.createdAt.toISOString(),action:event.action,userId:event.userId??"",settings:JSON.stringify(data.settings),payload:JSON.stringify(event.payload)})));audit.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};audit.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF17211D"}};return Buffer.from(await workbook.xlsx.writeBuffer());}
export async function loadExportData(context:ApiContext,runId:string):Promise<ExportData>{const run=await context.db.matchRun.findFirst({where:{id:runId,workspaceId:context.workspace.id},include:{links:{include:{invoice:true,txn:true}}}});if(!run)throw new ApiError(404,"MATCH_RUN_NOT_FOUND","Match run not found");const activeLinks=run.links.filter(link=>link.status!=="REJECTED"),linkedInvoiceIds=activeLinks.map(link=>link.invoiceId),linkedTxnIds=activeLinks.map(link=>link.txnId),[invoices,txns,audit]=await Promise.all([context.db.invoice.findMany({where:{workspaceId:context.workspace.id,uploadId:run.invoiceUploadId,id:{notIn:linkedInvoiceIds}}}),context.db.bankTxn.findMany({where:{workspaceId:context.workspace.id,uploadId:run.paymentUploadId,id:{notIn:linkedTxnIds}}}),context.db.auditEvent.findMany({where:{workspaceId:context.workspace.id},orderBy:{createdAt:"asc"}})]);return{runId:run.id,createdAt:run.createdAt,settings:run.settings,accountLabels:resolveAccountLabels(context.workspace.accountLabels),links:run.links,unmatchedInvoices:invoices,unallocatedIn:txns.filter(txn=>txn.amountMinor>0n),unallocatedOut:txns.filter(txn=>txn.amountMinor<0n),audit};}
export async function auditExport(context:ApiContext,runId:string,format:string){await context.db.auditEvent.create({data:{workspaceId:context.workspace.id,userId:context.user.id,action:"EXPORT",payload:{runId,format}}});}
