import type {ParsedInvoice,ParsedTxn} from "../parsers";
import {CURRENCY_EXPONENTS} from "../parsers/money";
import {assignmentOrder,isAutoLink,isEligible,type AssignmentCandidate} from "./assign";
import {bucketFor,flagsFor,type Bucket,type MatchFlag} from "./classify";
import {feeToleranceMinor,scorePair,type MatchSettings} from "./score";
import {literalIdentifierInDescription} from "./tokenize";
export type MatchMethod="EXACT_REF"|"FUZZY_REF"|"AMOUNT_DATE";
export type MatchLinkDraft={invoiceNumber:string;txnId:string;bucket:Bucket;method:MatchMethod;flags:MatchFlag[];expectedMinor:string;receivedMinor:string;feeMinor:string;fxDiffMinor:string;confidence:number;explanation:string};
export type Suggestion={type:"AMOUNT_DATE"|"POSSIBLE_BATCH";invoiceNumber?:string;invoiceNumbers?:string[];txnId:string;reason:string};
export type MatchResult={links:MatchLinkDraft[];unmatchedInvoices:ParsedInvoice[];unallocated_in:ParsedTxn[];unallocated_out:ParsedTxn[];suggestions:Suggestion[]};
type Detailed=AssignmentCandidate&{invoice:ParsedInvoice;txn:ParsedTxn;scored:ReturnType<typeof scorePair>};
type BatchSeed={txn:ParsedTxn;invoices:[ParsedInvoice,ParsedInvoice]};
function display(minor:bigint,currency:string,trim=false){const exponent=CURRENCY_EXPONENTS[currency as keyof typeof CURRENCY_EXPONENTS];if(exponent===undefined)return minor.toString();if(exponent===0)return minor.toString();const negative=minor<0n,absolute=(negative?-minor:minor).toString().padStart(exponent+1,"0"),value=`${negative?"-":""}${absolute.slice(0,-exponent)}.${absolute.slice(-exponent)}`;return trim?value.replace(/\.0+$/,""):value;}
function detail(invoice:ParsedInvoice,txn:ParsedTxn,openInvoices:ParsedInvoice[],settings:MatchSettings):Detailed{const scored=scorePair(invoice,txn,openInvoices,settings);return{invoice,txn,scored,invoiceNumber:invoice.invoiceNumber,txnId:txn.vendorId??txn.fingerprint,score:scored.score,strongId:scored.strongId,sameCurrency:scored.sameCurrency,insideWindow:scored.insideWindow,amountClass:scored.amountClass};}
function methodFor(item:Detailed):MatchMethod{const ids=[item.invoice.invoiceNumber,item.invoice.reference].filter((value):value is string=>Boolean(value));return ids.some(id=>literalIdentifierInDescription(item.txn.description,id))?"EXACT_REF":item.strongId?"FUZZY_REF":"AMOUNT_DATE";}
function explanation(item:Detailed){const {invoice,txn,scored}=item,why:string[]=[];if(scored.strongParts.invoiceNumber)why.push(`Exact invoice number ${invoice.invoiceNumber}`);if(scored.strongParts.reference&&invoice.reference)why.push(`reference ${invoice.reference} in description`);if(!why.length)why.push("Amount and date candidate");const expected=`${invoice.currency} ${display(invoice.amountMinor,invoice.currency)}`,delta=invoice.amountMinor-txn.amountMinor;let amount=`amount ${expected} equal`;if(scored.amountClass==="SHORT")amount=`amount ${expected} short by ${invoice.currency} ${display(delta,invoice.currency)}`;else if(scored.amountClass==="SHORT_OPEN")amount=`amount ${expected} underpaid beyond fee cap by ${invoice.currency} ${display(delta,invoice.currency)}`;else if(scored.amountClass==="OVER")amount=`amount ${expected} over by ${invoice.currency} ${display(-delta,invoice.currency)}`;const txnDay=Date.parse(`${scored.txnDate}T00:00:00Z`)/86400000,days=Math.round(txnDay-scored.dueDay),date=days===0?"value date on due date":`value date ${Math.abs(days)} day${Math.abs(days)===1?"":"s"} ${days>0?"after":"before"} due`;return`${why.join(" and ")}; ${amount}; ${date}.`;}
function makeLink(item:Detailed):MatchLinkDraft{const exponent=CURRENCY_EXPONENTS[item.invoice.currency as keyof typeof CURRENCY_EXPONENTS];if(exponent===undefined)throw new Error(`Unsupported currency ${item.invoice.currency}`);const flat=25n*10n**BigInt(exponent),short=item.scored.amountClass==="SHORT"||item.scored.amountClass==="SHORT_OPEN";return{invoiceNumber:item.invoice.invoiceNumber,txnId:item.txnId,bucket:bucketFor(item.invoice,item.txn,item.scored.amountClass),method:methodFor(item),flags:flagsFor(item.invoice,item.txn,item.scored.amountClass,flat),expectedMinor:item.invoice.amountMinor.toString(),receivedMinor:item.txn.amountMinor.toString(),feeMinor:(short?item.invoice.amountMinor-item.txn.amountMinor:0n).toString(),fxDiffMinor:"0",confidence:item.score,explanation:explanation(item)};}
function batchSeeds(invoices:ParsedInvoice[],txns:ParsedTxn[],settings:MatchSettings){const seeds:BatchSeed[]=[];for(const txn of txns){const same=invoices.filter(invoice=>invoice.currency===txn.currency),pairs:BatchSeed[]=[];for(let left=0;left<same.length;left++)for(let right=left+1;right<same.length;right++){const sum=same[left].amountMinor+same[right].amountMinor,difference=sum>txn.amountMinor?sum-txn.amountMinor:txn.amountMinor-sum;if(difference<=feeToleranceMinor(sum,txn.currency,settings))pairs.push({txn,invoices:[same[left],same[right]]});}if(pairs.length===1)seeds.push(pairs[0]);}return seeds;}
function amountDateReason(invoice:ParsedInvoice,txn:ParsedTxn,allInvoices:ParsedInvoice[],links:MatchLinkDraft[]){const consumed=allInvoices.find(candidate=>candidate.invoiceNumber!==invoice.invoiceNumber&&candidate.customerName===invoice.customerName&&candidate.currency===invoice.currency&&candidate.amountMinor===invoice.amountMinor&&links.some(link=>link.invoiceNumber===candidate.invoiceNumber));if(consumed){const link=links.find(candidate=>candidate.invoiceNumber===consumed.invoiceNumber)!;return`${consumed.invoiceNumber} already consumed by ${link.txnId}; ${txn.description} equals remaining ${invoice.customerName.split(/\s+/)[0]} ${invoice.currency} ${display(invoice.amountMinor,invoice.currency,true)}; no invoice number`;}return`Exact amount unique ${invoice.currency} ${display(invoice.amountMinor,invoice.currency,true)} and ${invoice.customerName.split(/\s+/)[0]} token; no reference`;}
export function runMatch(invoices:ParsedInvoice[],txns:ParsedTxn[],settings:MatchSettings={}):MatchResult{const inbound=txns.filter(txn=>txn.amountMinor>0n),outbound=txns.filter(txn=>txn.amountMinor<0n),seeds=batchSeeds(invoices,inbound,settings),usedInvoices=new Set<string>(),usedTxns=new Set<string>(),links:MatchLinkDraft[]=[];while(true){const openInvoices=invoices.filter(invoice=>!usedInvoices.has(invoice.invoiceNumber)),openTxns=inbound.filter(txn=>!usedTxns.has(txn.vendorId??txn.fingerprint)),next=openTxns.flatMap(txn=>openInvoices.map(invoice=>detail(invoice,txn,openInvoices,settings))).sort(assignmentOrder).find(candidate=>isAutoLink(candidate,settings));if(!next)break;usedInvoices.add(next.invoiceNumber);usedTxns.add(next.txnId);links.push(makeLink(next));}links.sort((a,b)=>a.invoiceNumber.localeCompare(b.invoiceNumber));const unmatchedInvoices=invoices.filter(invoice=>!usedInvoices.has(invoice.invoiceNumber)),unallocated_in=inbound.filter(txn=>!usedTxns.has(txn.vendorId??txn.fingerprint)),suggestions:Suggestion[]=[];for(const txn of unallocated_in)for(const invoice of unmatchedInvoices){const candidate=detail(invoice,txn,unmatchedInvoices,settings);if(isEligible(candidate))suggestions.push({type:"AMOUNT_DATE",invoiceNumber:invoice.invoiceNumber,txnId:candidate.txnId,reason:amountDateReason(invoice,txn,invoices,links)});}for(const seed of seeds){const txnId=seed.txn.vendorId??seed.txn.fingerprint;if(usedTxns.has(txnId)||seed.invoices.some(invoice=>usedInvoices.has(invoice.invoiceNumber)))continue;suggestions.push({type:"POSSIBLE_BATCH",txnId,invoiceNumbers:seed.invoices.map(invoice=>invoice.invoiceNumber),reason:`${display(seed.txn.amountMinor,seed.txn.currency)} equals ${display(seed.invoices[0].amountMinor,seed.txn.currency,true)}+${display(seed.invoices[1].amountMinor,seed.txn.currency,true)}; v1 will not auto-combine.`});}suggestions.sort((a,b)=>a.txnId.localeCompare(b.txnId));return{links,unmatchedInvoices,unallocated_in,unallocated_out:outbound,suggestions};}
