// Path A does not raise confidence. Golden floors for INV-1003/INV-1008/INV-1010 are raw scores 18/53/18.
// These weights are frozen; changing them requires a human-approved golden update. Golden minConfidence for INV-1004 is 50 because Path A auto-links without requiring 70; weights unchanged on 2026-08-31.
import type {ParsedInvoice,ParsedTxn} from "../parsers";
import {CURRENCY_EXPONENTS} from "../parsers/money";
import {hasDashOrSpaceVariant,hasFuzzyToken,sharesCustomerToken,strongIdentifier} from "./tokenize";
export type MatchSettings={dateWindowDaysBefore?:number;dateWindowDaysAfter?:number;feeToleranceBps?:number;feeFlatMajor?:number;feeCapMajor?:number;minAutoConfidence?:number;allowOneToMany?:boolean;allowManyToOne?:boolean};
export type AmountClass="EQUAL"|"SHORT"|"SHORT_OPEN"|"OVER"|"WILD";
export type ScoreReason={code:string;points:number};
const ceilDiv=(value:bigint,divisor:bigint)=>(value+divisor-1n)/divisor;
export function feeToleranceMinor(expected:bigint,currency:string,settings:MatchSettings={}){const exponent=CURRENCY_EXPONENTS[currency as keyof typeof CURRENCY_EXPONENTS];if(exponent===undefined)throw new Error(`Unsupported currency ${currency}`);const scale=10n**BigInt(exponent),bps=BigInt(settings.feeToleranceBps??30),flat=BigInt(settings.feeFlatMajor??25)*scale,cap=BigInt(settings.feeCapMajor??50)*scale,variable=ceilDiv(expected*bps,10000n);return variable<flat?flat:variable>cap?cap:variable;}
export function classifyAmount(expected:bigint,received:bigint,tolerance:bigint):AmountClass{const delta=expected-received,absolute=delta<0n?-delta:delta,fivePercent=ceilDiv(expected*5n,100n);if(absolute>(tolerance>fivePercent?tolerance:fivePercent))return"WILD";if(delta===0n)return"EQUAL";if(delta>0n&&delta<=tolerance)return"SHORT";if(delta>tolerance)return"SHORT_OPEN";return"OVER";}
const utcDate=(value:string)=>{const date=new Date(value);if(Number.isNaN(date.valueOf()))throw new Error(`Invalid date ${value}`);return date.toISOString().slice(0,10);};
const day=(value:string)=>Date.parse(`${utcDate(value)}T00:00:00Z`)/86400000;
export function scorePair(invoice:ParsedInvoice,txn:ParsedTxn,openInvoices:ParsedInvoice[],settings:MatchSettings={}){const reasons:ScoreReason[]=[],ids=strongIdentifier(invoice,txn),sameCurrency=invoice.currency===txn.currency,tolerance=sameCurrency?feeToleranceMinor(invoice.amountMinor,invoice.currency,settings):0n,amountClass=classifyAmount(invoice.amountMinor,txn.amountMinor,tolerance);if(ids.invoiceNumber)reasons.push({code:"INVOICE_NUMBER",points:40});if(ids.reference)reasons.push({code:"REFERENCE",points:25});if(hasDashOrSpaceVariant(invoice,txn)||(!ids.strong&&hasFuzzyToken(invoice,txn)))reasons.push({code:"FUZZY_ID",points:15});if(sameCurrency&&amountClass==="EQUAL")reasons.push({code:"AMOUNT_EQUAL",points:20});else if(sameCurrency&&amountClass==="SHORT")reasons.push({code:"AMOUNT_SHORT",points:10});const txnDate=txn.valueDate??txn.postedAt,due=day(invoice.dueDate),txnDay=day(txnDate),insideWindow=txnDay>=due-(settings.dateWindowDaysBefore??7)&&txnDay<=due+(settings.dateWindowDaysAfter??14);reasons.push(insideWindow?{code:"DATE_WINDOW",points:8}:{code:"DATE_OUTSIDE",points:-15});if(sharesCustomerToken(invoice,txn))reasons.push({code:"CUSTOMER_NAME",points:5});if(!ids.strong&&sameCurrency&&amountClass==="EQUAL"&&openInvoices.filter(candidate=>candidate.currency===invoice.currency&&candidate.amountMinor===txn.amountMinor).length===1)reasons.push({code:"UNIQUE_EQUAL",points:15});if(!sameCurrency)reasons.push({code:"CURRENCY_MISMATCH",points:-25});if(["SHORT_OPEN","OVER","WILD"].includes(amountClass))reasons.push({code:"AMOUNT_RISK",points:-20});const rawScore=reasons.reduce((sum,reason)=>sum+reason.points,0),score=Math.min(100,Math.max(0,rawScore));return{score,rawScore,reasons,strongId:ids.strong,strongParts:ids,sameCurrency,tolerance,amountClass,insideWindow,txnDate:utcDate(txnDate),dueDay:due};}
