import type {ParsedInvoice,ParsedTxn} from "../parsers";
const STOP=new Set(["LTD","LIMITED","INC","LLC","PAYMENT","BANK","TRANSFER","THE","WIRE","ACH"]);
export function tokenize(value:string){return value.toUpperCase().normalize("NFKD").replace(/[^A-Z0-9]+/g," ").trim().split(/\s+/).filter(Boolean);}
export function normalizeId(value:string){return tokenize(value).join("");}
function containsNormalized(source:string,id:string){const wanted=normalizeId(id),tokens=tokenize(source);if(!wanted)return false;if(tokens.some(token=>normalizeId(token)===wanted))return true;for(let start=0;start<tokens.length;start++){let joined="";for(let end=start;end<tokens.length;end++){joined+=tokens[end];if(joined===wanted)return true;if(joined.length>wanted.length)break;}}return false;}
export function literalIdentifierInDescription(description:string,id:string){const escaped=id.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(`(^|[^A-Z0-9])${escaped}([^A-Z0-9]|$)`,"i").test(description);}
export function strongIdentifier(invoice:ParsedInvoice,txn:ParsedTxn){const combined=`${txn.description} ${txn.reference??""}`,invoiceNumber=containsNormalized(combined,invoice.invoiceNumber),reference=invoice.reference?containsNormalized(combined,invoice.reference):false;return{strong:invoiceNumber||reference,invoiceNumber,reference};}
export function hasDashOrSpaceVariant(invoice:ParsedInvoice,txn:ParsedTxn){return[invoice.invoiceNumber,invoice.reference].filter((value):value is string=>Boolean(value)).some(id=>containsNormalized(txn.description,id)&&!literalIdentifierInDescription(txn.description,id));}
export function levenshtein(a:string,b:string){if(a===b)return 0;let previous=[...Array(b.length+1).keys()];for(let row=1;row<=a.length;row++){const next=[row];for(let column=1;column<=b.length;column++)next[column]=Math.min(next[column-1]+1,previous[column]+1,previous[column-1]+(a[row-1]===b[column-1]?0:1));previous=next;}return previous[b.length];}
export function hasFuzzyToken(invoice:ParsedInvoice,txn:ParsedTxn){const source=tokenize(txn.description),ids=[invoice.invoiceNumber,invoice.reference].filter((value):value is string=>Boolean(value)).map(normalizeId);return ids.some(id=>id.length>=6&&source.some(token=>token.length>=6&&levenshtein(id,normalizeId(token))<=1));}
export function sharesCustomerToken(invoice:ParsedInvoice,txn:ParsedTxn){const customer=new Set(tokenize(invoice.customerName).filter(token=>token.length>=4&&!STOP.has(token))),transaction=new Set(tokenize(`${txn.description} ${txn.counterparty??""}`).filter(token=>token.length>=4&&!STOP.has(token)));return[...customer].some(token=>transaction.has(token));}
