CREATE SCHEMA IF NOT EXISTS "public";
CREATE TYPE "Plan" AS ENUM ('STUDIO', 'COMMERCE');
CREATE TYPE "UploadKind" AS ENUM ('INVOICES', 'PAYMENTS');
CREATE TYPE "TxnSource" AS ENUM ('BANK', 'STRIPE', 'WISE', 'PAYONEER', 'GENERIC');
CREATE TYPE "MatchMethod" AS ENUM ('EXACT_REF', 'FUZZY_REF', 'AMOUNT_DATE', 'MANUAL');
CREATE TYPE "LinkStatus" AS ENUM ('PROPOSED', 'ACCEPTED', 'REJECTED');
CREATE TYPE "AuditAction" AS ENUM ('UPLOAD', 'RUN', 'ACCEPT', 'REJECT', 'MANUAL', 'EXPORT');
CREATE TABLE "User" ("id" TEXT NOT NULL, "clerkId" TEXT NOT NULL, "email" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Workspace" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "plan" "Plan" NOT NULL DEFAULT 'STUDIO', "stripeCustomerId" TEXT, "stripeSubscriptionId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Workspace_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Membership" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'owner', CONSTRAINT "Membership_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FileUpload" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "kind" "UploadKind" NOT NULL, "filename" TEXT NOT NULL, "byteSize" INTEGER NOT NULL, "sha256" TEXT NOT NULL, "parseErrors" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FileUpload_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Invoice" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "uploadId" TEXT, "externalId" TEXT, "invoiceNumber" TEXT NOT NULL, "customerName" TEXT NOT NULL, "currency" TEXT NOT NULL, "amountMinor" BIGINT NOT NULL, "issueDate" TIMESTAMP(3) NOT NULL, "dueDate" TIMESTAMP(3) NOT NULL, "reference" TEXT, "status" TEXT NOT NULL DEFAULT 'open', "rawJson" JSONB NOT NULL, "fingerprint" TEXT NOT NULL, CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BankTxn" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "uploadId" TEXT, "source" "TxnSource" NOT NULL, "vendorId" TEXT, "postedAt" TIMESTAMP(3) NOT NULL, "valueDate" TIMESTAMP(3), "currency" TEXT NOT NULL, "amountMinor" BIGINT NOT NULL, "description" TEXT NOT NULL, "counterparty" TEXT, "reference" TEXT, "endToEndId" TEXT, "rawJson" JSONB NOT NULL, "fingerprint" TEXT NOT NULL, CONSTRAINT "BankTxn_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MatchRun" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "invoiceUploadId" TEXT NOT NULL, "paymentUploadId" TEXT NOT NULL, "settings" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MatchRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MatchLink" ("id" TEXT NOT NULL, "runId" TEXT NOT NULL, "invoiceId" TEXT NOT NULL, "txnId" TEXT NOT NULL, "confidence" INTEGER NOT NULL, "method" "MatchMethod" NOT NULL, "flags" TEXT[], "status" "LinkStatus" NOT NULL DEFAULT 'PROPOSED', "expectedMinor" BIGINT NOT NULL, "receivedMinor" BIGINT NOT NULL, "feeMinor" BIGINT NOT NULL DEFAULT 0, "fxDiffMinor" BIGINT NOT NULL DEFAULT 0, "explanation" TEXT NOT NULL, CONSTRAINT "MatchLink_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditEvent" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "userId" TEXT, "action" "AuditAction" NOT NULL, "payload" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_clerkId_key" ON "User"("clerkId");
CREATE UNIQUE INDEX "Membership_workspaceId_userId_key" ON "Membership"("workspaceId", "userId");
CREATE UNIQUE INDEX "Invoice_workspaceId_fingerprint_key" ON "Invoice"("workspaceId", "fingerprint");
CREATE UNIQUE INDEX "BankTxn_workspaceId_fingerprint_key" ON "BankTxn"("workspaceId", "fingerprint");
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FileUpload" ADD CONSTRAINT "FileUpload_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BankTxn" ADD CONSTRAINT "BankTxn_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MatchRun" ADD CONSTRAINT "MatchRun_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MatchLink" ADD CONSTRAINT "MatchLink_runId_fkey" FOREIGN KEY ("runId") REFERENCES "MatchRun"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MatchLink" ADD CONSTRAINT "MatchLink_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MatchLink" ADD CONSTRAINT "MatchLink_txnId_fkey" FOREIGN KEY ("txnId") REFERENCES "BankTxn"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
