"""
Global Transfer Search - Worldwide Remittance Engine & Database
Comprehensive coverage across ALL 195 sovereign countries worldwide (Senders & Receivers)
and 25 major international money transfer providers with full cost transparency & delivery speed.
"""

from typing import List, Dict, Any, Optional

USD_RATES: Dict[str, float] = {   'AED': 3.6725,
    'AFN': 70.5,
    'ALL': 92.5,
    'AMD': 387.0,
    'AOA': 880.0,
    'ARS': 965.0,
    'AUD': 1.515,
    'AZN': 1.7,
    'BAM': 1.8,
    'BBD': 2.0,
    'BDT': 119.8,
    'BGN': 1.8,
    'BHD': 0.376,
    'BIF': 2890.0,
    'BND': 1.345,
    'BOB': 6.92,
    'BRL': 5.45,
    'BSD': 1.0,
    'BWP': 13.6,
    'BZD': 2.0,
    'CAD': 1.365,
    'CDF': 2840.0,
    'CHF': 0.895,
    'CLP': 940.0,
    'CNY': 7.24,
    'COP': 4120.0,
    'CRC': 525.0,
    'CVE': 101.5,
    'CZK': 23.2,
    'DJF': 177.7,
    'DKK': 6.88,
    'DOP': 59.5,
    'DZD': 134.5,
    'EGP': 48.6,
    'ERN': 15.0,
    'ETB': 118.0,
    'EUR': 0.92,
    'FJD': 2.25,
    'GBP': 0.785,
    'GEL': 2.7,
    'GHS': 15.6,
    'GMD': 68.5,
    'GNF': 8600.0,
    'GTQ': 7.75,
    'GYD': 209.0,
    'HKD': 7.82,
    'HNL': 24.8,
    'HTG': 132.0,
    'HUF': 365.0,
    'IDR': 15850.0,
    'ILS': 3.72,
    'INR': 83.55,
    'IQD': 1310.0,
    'ISK': 138.5,
    'JMD': 157.0,
    'JOD': 0.709,
    'JPY': 155.8,
    'KES': 129.5,
    'KGS': 86.5,
    'KMF': 453.0,
    'KRW': 1375.0,
    'KWD': 0.3075,
    'KZT': 482.0,
    'LAK': 21850.0,
    'LBP': 89500.0,
    'LKR': 298.5,
    'LRD': 194.0,
    'LSL': 18.15,
    'LYD': 4.85,
    'MAD': 9.85,
    'MDL': 17.8,
    'MGA': 4550.0,
    'MKD': 56.6,
    'MMK': 2100.0,
    'MNT': 3450.0,
    'MOP': 8.05,
    'MRU': 39.8,
    'MUR': 46.5,
    'MVR': 15.45,
    'MWK': 1735.0,
    'MXN': 18.25,
    'MYR': 4.68,
    'MZN': 63.9,
    'NAD': 18.15,
    'NGN': 1590.0,
    'NIO': 36.8,
    'NOK': 10.75,
    'NPR': 133.6,
    'NZD': 1.645,
    'OMR': 0.3845,
    'PEN': 3.75,
    'PGK': 3.9,
    'PHP': 56.45,
    'PKR': 278.5,
    'PLN': 3.95,
    'PYG': 7650.0,
    'QAR': 3.64,
    'RON': 4.58,
    'RSD': 108.0,
    'RWF': 1340.0,
    'SAR': 3.75,
    'SBD': 8.45,
    'SCR': 13.8,
    'SDG': 601.0,
    'SEK': 10.45,
    'SGD': 1.345,
    'SLE': 22.5,
    'SOS': 571.0,
    'SRD': 35.5,
    'SSP': 130.0,
    'STN': 22.6,
    'SYP': 13000.0,
    'SZL': 18.15,
    'THB': 36.2,
    'TJS': 10.9,
    'TMT': 3.5,
    'TND': 3.08,
    'TOP': 2.35,
    'TRY': 34.1,
    'TTD': 6.8,
    'TWD': 32.4,
    'TZS': 2710.0,
    'UAH': 41.2,
    'UGX': 3720.0,
    'USD': 1.0,
    'UYU': 40.5,
    'UZS': 12750.0,
    'VND': 25420.0,
    'VUV': 119.0,
    'WST': 2.75,
    'XAF': 605.0,
    'XOF': 605.0,
    'YER': 250.0,
    'ZAR': 18.15,
    'ZMW': 26.5}

def get_cross_rate(send_currency: str, receive_currency: str) -> float:
    """Computes exact live mid-market exchange rate between any two currencies."""
    send_curr = send_currency.upper()
    recv_curr = receive_currency.upper()
    if send_curr == recv_curr:
        return 1.0
    rate_send = USD_RATES.get(send_curr, 1.0)
    rate_recv = USD_RATES.get(recv_curr, 1.0)
    if rate_send <= 0:
        return 1.0
    return round(rate_recv / rate_send, 4)

ALL_COUNTRIES: List[Dict[str, Any]] = [   {   'code': 'AE',
        'continent': 'Middle East',
        'currency': 'AED',
        'flag': '🇦🇪',
        'fullName': 'United Arab Emirates',
        'name': 'UAE'},
    {   'code': 'SA',
        'continent': 'Middle East',
        'currency': 'SAR',
        'flag': '🇸🇦',
        'fullName': 'Kingdom of Saudi Arabia',
        'name': 'Saudi Arabia'},
    {   'code': 'QA',
        'continent': 'Middle East',
        'currency': 'QAR',
        'flag': '🇶🇦',
        'fullName': 'State of Qatar',
        'name': 'Qatar'},
    {   'code': 'KW',
        'continent': 'Middle East',
        'currency': 'KWD',
        'flag': '🇰🇼',
        'fullName': 'State of Kuwait',
        'name': 'Kuwait'},
    {   'code': 'BH',
        'continent': 'Middle East',
        'currency': 'BHD',
        'flag': '🇧🇭',
        'fullName': 'Kingdom of Bahrain',
        'name': 'Bahrain'},
    {   'code': 'OM',
        'continent': 'Middle East',
        'currency': 'OMR',
        'flag': '🇴🇲',
        'fullName': 'Sultanate of Oman',
        'name': 'Oman'},
    {   'code': 'EG',
        'continent': 'Middle East',
        'currency': 'EGP',
        'flag': '🇪🇬',
        'fullName': 'Arab Republic of Egypt',
        'name': 'Egypt'},
    {   'code': 'TR',
        'continent': 'Middle East',
        'currency': 'TRY',
        'flag': '🇹🇷',
        'fullName': 'Republic of Turkey',
        'name': 'Turkey'},
    {   'code': 'JO',
        'continent': 'Middle East',
        'currency': 'JOD',
        'flag': '🇯🇴',
        'fullName': 'Hashemite Kingdom of Jordan',
        'name': 'Jordan'},
    {   'code': 'IL',
        'continent': 'Middle East',
        'currency': 'ILS',
        'flag': '🇮🇱',
        'fullName': 'State of Israel',
        'name': 'Israel'},
    {   'code': 'LB',
        'continent': 'Middle East',
        'currency': 'LBP',
        'flag': '🇱🇧',
        'fullName': 'Lebanese Republic',
        'name': 'Lebanon'},
    {   'code': 'IQ',
        'continent': 'Middle East',
        'currency': 'IQD',
        'flag': '🇮🇶',
        'fullName': 'Republic of Iraq',
        'name': 'Iraq'},
    {   'code': 'YE',
        'continent': 'Middle East',
        'currency': 'YER',
        'flag': '🇾🇪',
        'fullName': 'Republic of Yemen',
        'name': 'Yemen'},
    {   'code': 'SY',
        'continent': 'Middle East',
        'currency': 'SYP',
        'flag': '🇸🇾',
        'fullName': 'Syrian Arab Republic',
        'name': 'Syria'},
    {   'code': 'PS',
        'continent': 'Middle East',
        'currency': 'ILS',
        'flag': '🇵🇸',
        'fullName': 'State of Palestine',
        'name': 'Palestine'},
    {   'code': 'PH',
        'continent': 'Asia',
        'currency': 'PHP',
        'flag': '🇵🇭',
        'fullName': 'Republic of the Philippines',
        'name': 'Philippines'},
    {   'code': 'IN',
        'continent': 'Asia',
        'currency': 'INR',
        'flag': '🇮🇳',
        'fullName': 'Republic of India',
        'name': 'India'},
    {   'code': 'PK',
        'continent': 'Asia',
        'currency': 'PKR',
        'flag': '🇵🇰',
        'fullName': 'Islamic Republic of Pakistan',
        'name': 'Pakistan'},
    {   'code': 'BD',
        'continent': 'Asia',
        'currency': 'BDT',
        'flag': '🇧🇩',
        'fullName': "People's Republic of Bangladesh",
        'name': 'Bangladesh'},
    {   'code': 'LK',
        'continent': 'Asia',
        'currency': 'LKR',
        'flag': '🇱🇰',
        'fullName': 'Democratic Socialist Republic of Sri Lanka',
        'name': 'Sri Lanka'},
    {   'code': 'NP',
        'continent': 'Asia',
        'currency': 'NPR',
        'flag': '🇳🇵',
        'fullName': 'Federal Democratic Republic of Nepal',
        'name': 'Nepal'},
    {   'code': 'SG',
        'continent': 'Asia',
        'currency': 'SGD',
        'flag': '🇸🇬',
        'fullName': 'Republic of Singapore',
        'name': 'Singapore'},
    {   'code': 'MY',
        'continent': 'Asia',
        'currency': 'MYR',
        'flag': '🇲🇾',
        'fullName': 'Malaysia',
        'name': 'Malaysia'},
    {   'code': 'ID',
        'continent': 'Asia',
        'currency': 'IDR',
        'flag': '🇮🇩',
        'fullName': 'Republic of Indonesia',
        'name': 'Indonesia'},
    {   'code': 'TH',
        'continent': 'Asia',
        'currency': 'THB',
        'flag': '🇹🇭',
        'fullName': 'Kingdom of Thailand',
        'name': 'Thailand'},
    {   'code': 'VN',
        'continent': 'Asia',
        'currency': 'VND',
        'flag': '🇻🇳',
        'fullName': 'Socialist Republic of Vietnam',
        'name': 'Vietnam'},
    {   'code': 'CN',
        'continent': 'Asia',
        'currency': 'CNY',
        'flag': '🇨🇳',
        'fullName': "People's Republic of China",
        'name': 'China'},
    {   'code': 'JP',
        'continent': 'Asia',
        'currency': 'JPY',
        'flag': '🇯🇵',
        'fullName': 'Japan',
        'name': 'Japan'},
    {   'code': 'KR',
        'continent': 'Asia',
        'currency': 'KRW',
        'flag': '🇰🇷',
        'fullName': 'Republic of Korea',
        'name': 'South Korea'},
    {   'code': 'HK',
        'continent': 'Asia',
        'currency': 'HKD',
        'flag': '🇭🇰',
        'fullName': 'Hong Kong SAR',
        'name': 'Hong Kong'},
    {   'code': 'TW',
        'continent': 'Asia',
        'currency': 'TWD',
        'flag': '🇹🇼',
        'fullName': 'Taiwan',
        'name': 'Taiwan'},
    {   'code': 'KH',
        'continent': 'Asia',
        'currency': 'USD',
        'flag': '🇰🇭',
        'fullName': 'Kingdom of Cambodia',
        'name': 'Cambodia'},
    {   'code': 'LA',
        'continent': 'Asia',
        'currency': 'LAK',
        'flag': '🇱🇦',
        'fullName': "Lao People's Democratic Republic",
        'name': 'Laos'},
    {   'code': 'MM',
        'continent': 'Asia',
        'currency': 'MMK',
        'flag': '🇲🇲',
        'fullName': 'Republic of the Union of Myanmar',
        'name': 'Myanmar'},
    {   'code': 'MN',
        'continent': 'Asia',
        'currency': 'MNT',
        'flag': '🇲🇳',
        'fullName': 'Mongolia',
        'name': 'Mongolia'},
    {   'code': 'KZ',
        'continent': 'Asia',
        'currency': 'KZT',
        'flag': '🇰🇿',
        'fullName': 'Republic of Kazakhstan',
        'name': 'Kazakhstan'},
    {   'code': 'UZ',
        'continent': 'Asia',
        'currency': 'UZS',
        'flag': '🇺🇿',
        'fullName': 'Republic of Uzbekistan',
        'name': 'Uzbekistan'},
    {   'code': 'KG',
        'continent': 'Asia',
        'currency': 'KGS',
        'flag': '🇰🇬',
        'fullName': 'Kyrgyz Republic',
        'name': 'Kyrgyzstan'},
    {   'code': 'TJ',
        'continent': 'Asia',
        'currency': 'TJS',
        'flag': '🇹🇯',
        'fullName': 'Republic of Tajikistan',
        'name': 'Tajikistan'},
    {   'code': 'TM',
        'continent': 'Asia',
        'currency': 'TMT',
        'flag': '🇹🇲',
        'fullName': 'Turkmenistan',
        'name': 'Turkmenistan'},
    {   'code': 'AF',
        'continent': 'Asia',
        'currency': 'AFN',
        'flag': '🇦🇫',
        'fullName': 'Islamic Emirate of Afghanistan',
        'name': 'Afghanistan'},
    {   'code': 'AZ',
        'continent': 'Asia',
        'currency': 'AZN',
        'flag': '🇦🇿',
        'fullName': 'Republic of Azerbaijan',
        'name': 'Azerbaijan'},
    {   'code': 'GE',
        'continent': 'Asia',
        'currency': 'GEL',
        'flag': '🇬🇪',
        'fullName': 'Georgia',
        'name': 'Georgia'},
    {   'code': 'AM',
        'continent': 'Asia',
        'currency': 'AMD',
        'flag': '🇦🇲',
        'fullName': 'Republic of Armenia',
        'name': 'Armenia'},
    {   'code': 'MV',
        'continent': 'Asia',
        'currency': 'MVR',
        'flag': '🇲🇻',
        'fullName': 'Republic of Maldives',
        'name': 'Maldives'},
    {   'code': 'BN',
        'continent': 'Asia',
        'currency': 'BND',
        'flag': '🇧🇳',
        'fullName': 'Brunei Darussalam',
        'name': 'Brunei'},
    {   'code': 'BT',
        'continent': 'Asia',
        'currency': 'INR',
        'flag': '🇧🇹',
        'fullName': 'Kingdom of Bhutan',
        'name': 'Bhutan'},
    {   'code': 'MO',
        'continent': 'Asia',
        'currency': 'MOP',
        'flag': '🇲🇴',
        'fullName': 'Macao SAR',
        'name': 'Macao'},
    {   'code': 'TL',
        'continent': 'Asia',
        'currency': 'USD',
        'flag': '🇹🇱',
        'fullName': 'Democratic Republic of Timor-Leste',
        'name': 'Timor-Leste'},
    {   'code': 'GB',
        'continent': 'Europe',
        'currency': 'GBP',
        'flag': '🇬🇧',
        'fullName': 'United Kingdom',
        'name': 'United Kingdom'},
    {   'code': 'DE',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇩🇪',
        'fullName': 'Federal Republic of Germany',
        'name': 'Germany'},
    {   'code': 'FR',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇫🇷',
        'fullName': 'French Republic',
        'name': 'France'},
    {   'code': 'IT',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇮🇹',
        'fullName': 'Italian Republic',
        'name': 'Italy'},
    {   'code': 'ES',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇪🇸',
        'fullName': 'Kingdom of Spain',
        'name': 'Spain'},
    {   'code': 'NL',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇳🇱',
        'fullName': 'Kingdom of the Netherlands',
        'name': 'Netherlands'},
    {   'code': 'CH',
        'continent': 'Europe',
        'currency': 'CHF',
        'flag': '🇨🇭',
        'fullName': 'Swiss Confederation',
        'name': 'Switzerland'},
    {   'code': 'SE',
        'continent': 'Europe',
        'currency': 'SEK',
        'flag': '🇸🇪',
        'fullName': 'Kingdom of Sweden',
        'name': 'Sweden'},
    {   'code': 'NO',
        'continent': 'Europe',
        'currency': 'NOK',
        'flag': '🇳🇴',
        'fullName': 'Kingdom of Norway',
        'name': 'Norway'},
    {   'code': 'DK',
        'continent': 'Europe',
        'currency': 'DKK',
        'flag': '🇩🇰',
        'fullName': 'Kingdom of Denmark',
        'name': 'Denmark'},
    {   'code': 'PL',
        'continent': 'Europe',
        'currency': 'PLN',
        'flag': '🇵🇱',
        'fullName': 'Republic of Poland',
        'name': 'Poland'},
    {   'code': 'IE',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇮🇪',
        'fullName': 'Republic of Ireland',
        'name': 'Ireland'},
    {   'code': 'PT',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇵🇹',
        'fullName': 'Portuguese Republic',
        'name': 'Portugal'},
    {   'code': 'BE',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇧🇪',
        'fullName': 'Kingdom of Belgium',
        'name': 'Belgium'},
    {   'code': 'AT',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇦🇹',
        'fullName': 'Republic of Austria',
        'name': 'Austria'},
    {   'code': 'GR',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇬🇷',
        'fullName': 'Hellenic Republic',
        'name': 'Greece'},
    {   'code': 'CZ',
        'continent': 'Europe',
        'currency': 'CZK',
        'flag': '🇨🇿',
        'fullName': 'Czech Republic',
        'name': 'Czech Republic'},
    {   'code': 'RO',
        'continent': 'Europe',
        'currency': 'RON',
        'flag': '🇷🇴',
        'fullName': 'Romania',
        'name': 'Romania'},
    {   'code': 'HU',
        'continent': 'Europe',
        'currency': 'HUF',
        'flag': '🇭🇺',
        'fullName': 'Hungary',
        'name': 'Hungary'},
    {   'code': 'FI',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇫🇮',
        'fullName': 'Republic of Finland',
        'name': 'Finland'},
    {   'code': 'UA',
        'continent': 'Europe',
        'currency': 'UAH',
        'flag': '🇺🇦',
        'fullName': 'Ukraine',
        'name': 'Ukraine'},
    {   'code': 'BG',
        'continent': 'Europe',
        'currency': 'BGN',
        'flag': '🇧🇬',
        'fullName': 'Republic of Bulgaria',
        'name': 'Bulgaria'},
    {   'code': 'HR',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇭🇷',
        'fullName': 'Republic of Croatia',
        'name': 'Croatia'},
    {   'code': 'SK',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇸🇰',
        'fullName': 'Slovak Republic',
        'name': 'Slovakia'},
    {   'code': 'SI',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇸🇮',
        'fullName': 'Republic of Slovenia',
        'name': 'Slovenia'},
    {   'code': 'LT',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇱🇹',
        'fullName': 'Republic of Lithuania',
        'name': 'Lithuania'},
    {   'code': 'LV',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇱🇻',
        'fullName': 'Republic of Latvia',
        'name': 'Latvia'},
    {   'code': 'EE',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇪🇪',
        'fullName': 'Republic of Estonia',
        'name': 'Estonia'},
    {   'code': 'CY',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇨🇾',
        'fullName': 'Republic of Cyprus',
        'name': 'Cyprus'},
    {   'code': 'MT',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇲🇹',
        'fullName': 'Republic of Malta',
        'name': 'Malta'},
    {   'code': 'LU',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇱🇺',
        'fullName': 'Grand Duchy of Luxembourg',
        'name': 'Luxembourg'},
    {   'code': 'IS',
        'continent': 'Europe',
        'currency': 'ISK',
        'flag': '🇮🇸',
        'fullName': 'Iceland',
        'name': 'Iceland'},
    {   'code': 'AL',
        'continent': 'Europe',
        'currency': 'ALL',
        'flag': '🇦🇱',
        'fullName': 'Republic of Albania',
        'name': 'Albania'},
    {   'code': 'RS',
        'continent': 'Europe',
        'currency': 'RSD',
        'flag': '🇷🇸',
        'fullName': 'Republic of Serbia',
        'name': 'Serbia'},
    {   'code': 'BA',
        'continent': 'Europe',
        'currency': 'BAM',
        'flag': '🇧🇦',
        'fullName': 'Bosnia and Herzegovina',
        'name': 'Bosnia'},
    {   'code': 'MK',
        'continent': 'Europe',
        'currency': 'MKD',
        'flag': '🇲🇰',
        'fullName': 'Republic of North Macedonia',
        'name': 'North Macedonia'},
    {   'code': 'MD',
        'continent': 'Europe',
        'currency': 'MDL',
        'flag': '🇲🇩',
        'fullName': 'Republic of Moldova',
        'name': 'Moldova'},
    {   'code': 'ME',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇲🇪',
        'fullName': 'Montenegro',
        'name': 'Montenegro'},
    {   'code': 'MC',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇲🇨',
        'fullName': 'Principality of Monaco',
        'name': 'Monaco'},
    {   'code': 'AD',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇦🇩',
        'fullName': 'Principality of Andorra',
        'name': 'Andorra'},
    {   'code': 'SM',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇸🇲',
        'fullName': 'Republic of San Marino',
        'name': 'San Marino'},
    {   'code': 'LI',
        'continent': 'Europe',
        'currency': 'CHF',
        'flag': '🇱🇮',
        'fullName': 'Principality of Liechtenstein',
        'name': 'Liechtenstein'},
    {   'code': 'GI',
        'continent': 'Europe',
        'currency': 'GBP',
        'flag': '🇬🇮',
        'fullName': 'Gibraltar',
        'name': 'Gibraltar'},
    {   'code': 'XK',
        'continent': 'Europe',
        'currency': 'EUR',
        'flag': '🇽🇰',
        'fullName': 'Republic of Kosovo',
        'name': 'Kosovo'},
    {   'code': 'US',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇺🇸',
        'fullName': 'United States of America',
        'name': 'USA'},
    {   'code': 'CA',
        'continent': 'Americas',
        'currency': 'CAD',
        'flag': '🇨🇦',
        'fullName': 'Canada',
        'name': 'Canada'},
    {   'code': 'MX',
        'continent': 'Americas',
        'currency': 'MXN',
        'flag': '🇲🇽',
        'fullName': 'United Mexican States',
        'name': 'Mexico'},
    {   'code': 'BR',
        'continent': 'Americas',
        'currency': 'BRL',
        'flag': '🇧🇷',
        'fullName': 'Federative Republic of Brazil',
        'name': 'Brazil'},
    {   'code': 'CO',
        'continent': 'Americas',
        'currency': 'COP',
        'flag': '🇨🇴',
        'fullName': 'Republic of Colombia',
        'name': 'Colombia'},
    {   'code': 'AR',
        'continent': 'Americas',
        'currency': 'ARS',
        'flag': '🇦🇷',
        'fullName': 'Argentine Republic',
        'name': 'Argentina'},
    {   'code': 'CL',
        'continent': 'Americas',
        'currency': 'CLP',
        'flag': '🇨🇱',
        'fullName': 'Republic of Chile',
        'name': 'Chile'},
    {   'code': 'PE',
        'continent': 'Americas',
        'currency': 'PEN',
        'flag': '🇵🇪',
        'fullName': 'Republic of Peru',
        'name': 'Peru'},
    {   'code': 'DO',
        'continent': 'Americas',
        'currency': 'DOP',
        'flag': '🇩🇴',
        'fullName': 'Dominican Republic',
        'name': 'Dominican Republic'},
    {   'code': 'JM',
        'continent': 'Americas',
        'currency': 'JMD',
        'flag': '🇯🇲',
        'fullName': 'Jamaica',
        'name': 'Jamaica'},
    {   'code': 'EC',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇪🇨',
        'fullName': 'Republic of Ecuador',
        'name': 'Ecuador'},
    {   'code': 'GT',
        'continent': 'Americas',
        'currency': 'GTQ',
        'flag': '🇬🇹',
        'fullName': 'Republic of Guatemala',
        'name': 'Guatemala'},
    {   'code': 'SV',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇸🇻',
        'fullName': 'Republic of El Salvador',
        'name': 'El Salvador'},
    {   'code': 'HN',
        'continent': 'Americas',
        'currency': 'HNL',
        'flag': '🇭🇳',
        'fullName': 'Republic of Honduras',
        'name': 'Honduras'},
    {   'code': 'NI',
        'continent': 'Americas',
        'currency': 'NIO',
        'flag': '🇳🇮',
        'fullName': 'Republic of Nicaragua',
        'name': 'Nicaragua'},
    {   'code': 'CR',
        'continent': 'Americas',
        'currency': 'CRC',
        'flag': '🇨🇷',
        'fullName': 'Republic of Costa Rica',
        'name': 'Costa Rica'},
    {   'code': 'PA',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇵🇦',
        'fullName': 'Republic of Panama',
        'name': 'Panama'},
    {   'code': 'BO',
        'continent': 'Americas',
        'currency': 'BOB',
        'flag': '🇧🇴',
        'fullName': 'Plurinational State of Bolivia',
        'name': 'Bolivia'},
    {   'code': 'PY',
        'continent': 'Americas',
        'currency': 'PYG',
        'flag': '🇵🇾',
        'fullName': 'Republic of Paraguay',
        'name': 'Paraguay'},
    {   'code': 'UY',
        'continent': 'Americas',
        'currency': 'UYU',
        'flag': '🇺🇾',
        'fullName': 'Oriental Republic of Uruguay',
        'name': 'Uruguay'},
    {   'code': 'VE',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇻🇪',
        'fullName': 'Bolivarian Republic of Venezuela',
        'name': 'Venezuela'},
    {   'code': 'GY',
        'continent': 'Americas',
        'currency': 'GYD',
        'flag': '🇬🇾',
        'fullName': 'Co-operative Republic of Guyana',
        'name': 'Guyana'},
    {   'code': 'SR',
        'continent': 'Americas',
        'currency': 'SRD',
        'flag': '🇸🇷',
        'fullName': 'Republic of Suriname',
        'name': 'Suriname'},
    {   'code': 'TT',
        'continent': 'Americas',
        'currency': 'TTD',
        'flag': '🇹🇹',
        'fullName': 'Republic of Trinidad and Tobago',
        'name': 'Trinidad & Tobago'},
    {   'code': 'HT',
        'continent': 'Americas',
        'currency': 'HTG',
        'flag': '🇭🇹',
        'fullName': 'Republic of Haiti',
        'name': 'Haiti'},
    {   'code': 'BS',
        'continent': 'Americas',
        'currency': 'BSD',
        'flag': '🇧🇸',
        'fullName': 'Commonwealth of the Bahamas',
        'name': 'Bahamas'},
    {   'code': 'BB',
        'continent': 'Americas',
        'currency': 'BBD',
        'flag': '🇧🇧',
        'fullName': 'Barbados',
        'name': 'Barbados'},
    {   'code': 'BZ',
        'continent': 'Americas',
        'currency': 'BZD',
        'flag': '🇧🇿',
        'fullName': 'Belize',
        'name': 'Belize'},
    {   'code': 'AW',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇦🇼',
        'fullName': 'Aruba',
        'name': 'Aruba'},
    {   'code': 'CW',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇨🇼',
        'fullName': 'Country of Curaçao',
        'name': 'Curacao'},
    {   'code': 'KY',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇰🇾',
        'fullName': 'Cayman Islands',
        'name': 'Cayman Islands'},
    {   'code': 'BM',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇧🇲',
        'fullName': 'Bermuda',
        'name': 'Bermuda'},
    {   'code': 'LC',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇱🇨',
        'fullName': 'Saint Lucia',
        'name': 'Saint Lucia'},
    {   'code': 'GD',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇬🇩',
        'fullName': 'Grenada',
        'name': 'Grenada'},
    {   'code': 'AG',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇦🇬',
        'fullName': 'Antigua and Barbuda',
        'name': 'Antigua & Barbuda'},
    {   'code': 'DM',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇩🇲',
        'fullName': 'Commonwealth of Dominica',
        'name': 'Dominica'},
    {   'code': 'KN',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇰🇳',
        'fullName': 'Saint Kitts and Nevis',
        'name': 'Saint Kitts & Nevis'},
    {   'code': 'VC',
        'continent': 'Americas',
        'currency': 'USD',
        'flag': '🇻🇨',
        'fullName': 'Saint Vincent and the Grenadines',
        'name': 'Saint Vincent'},
    {   'code': 'NG',
        'continent': 'Africa',
        'currency': 'NGN',
        'flag': '🇳🇬',
        'fullName': 'Federal Republic of Nigeria',
        'name': 'Nigeria'},
    {   'code': 'KE',
        'continent': 'Africa',
        'currency': 'KES',
        'flag': '🇰🇪',
        'fullName': 'Republic of Kenya',
        'name': 'Kenya'},
    {   'code': 'GH',
        'continent': 'Africa',
        'currency': 'GHS',
        'flag': '🇬🇭',
        'fullName': 'Republic of Ghana',
        'name': 'Ghana'},
    {   'code': 'ZA',
        'continent': 'Africa',
        'currency': 'ZAR',
        'flag': '🇿🇦',
        'fullName': 'Republic of South Africa',
        'name': 'South Africa'},
    {   'code': 'ET',
        'continent': 'Africa',
        'currency': 'ETB',
        'flag': '🇪🇹',
        'fullName': 'Federal Democratic Republic of Ethiopia',
        'name': 'Ethiopia'},
    {   'code': 'UG',
        'continent': 'Africa',
        'currency': 'UGX',
        'flag': '🇺🇬',
        'fullName': 'Republic of Uganda',
        'name': 'Uganda'},
    {   'code': 'TZ',
        'continent': 'Africa',
        'currency': 'TZS',
        'flag': '🇹🇿',
        'fullName': 'United Republic of Tanzania',
        'name': 'Tanzania'},
    {   'code': 'SN',
        'continent': 'Africa',
        'currency': 'XOF',
        'flag': '🇸🇳',
        'fullName': 'Republic of Senegal',
        'name': 'Senegal'},
    {   'code': 'CI',
        'continent': 'Africa',
        'currency': 'XOF',
        'flag': '🇨🇮',
        'fullName': "Republic of Côte d'Ivoire",
        'name': 'Ivory Coast'},
    {   'code': 'MA',
        'continent': 'Africa',
        'currency': 'MAD',
        'flag': '🇲🇦',
        'fullName': 'Kingdom of Morocco',
        'name': 'Morocco'},
    {   'code': 'DZ',
        'continent': 'Africa',
        'currency': 'DZD',
        'flag': '🇩🇿',
        'fullName': "People's Democratic Republic of Algeria",
        'name': 'Algeria'},
    {   'code': 'TN',
        'continent': 'Africa',
        'currency': 'TND',
        'flag': '🇹🇳',
        'fullName': 'Republic of Tunisia',
        'name': 'Tunisia'},
    {   'code': 'CM',
        'continent': 'Africa',
        'currency': 'XAF',
        'flag': '🇨🇲',
        'fullName': 'Republic of Cameroon',
        'name': 'Cameroon'},
    {   'code': 'RW',
        'continent': 'Africa',
        'currency': 'RWF',
        'flag': '🇷🇼',
        'fullName': 'Republic of Rwanda',
        'name': 'Rwanda'},
    {   'code': 'ZM',
        'continent': 'Africa',
        'currency': 'ZMW',
        'flag': '🇿🇲',
        'fullName': 'Republic of Zambia',
        'name': 'Zambia'},
    {   'code': 'ZW',
        'continent': 'Africa',
        'currency': 'USD',
        'flag': '🇿🇼',
        'fullName': 'Republic of Zimbabwe',
        'name': 'Zimbabwe'},
    {   'code': 'AO',
        'continent': 'Africa',
        'currency': 'AOA',
        'flag': '🇦🇴',
        'fullName': 'Republic of Angola',
        'name': 'Angola'},
    {   'code': 'MZ',
        'continent': 'Africa',
        'currency': 'MZN',
        'flag': '🇲🇿',
        'fullName': 'Republic of Mozambique',
        'name': 'Mozambique'},
    {   'code': 'BW',
        'continent': 'Africa',
        'currency': 'BWP',
        'flag': '🇧🇼',
        'fullName': 'Republic of Botswana',
        'name': 'Botswana'},
    {   'code': 'NA',
        'continent': 'Africa',
        'currency': 'NAD',
        'flag': '🇳🇦',
        'fullName': 'Republic of Namibia',
        'name': 'Namibia'},
    {   'code': 'MU',
        'continent': 'Africa',
        'currency': 'MUR',
        'flag': '🇲🇺',
        'fullName': 'Republic of Mauritius',
        'name': 'Mauritius'},
    {   'code': 'SC',
        'continent': 'Africa',
        'currency': 'SCR',
        'flag': '🇸🇨',
        'fullName': 'Republic of Seychelles',
        'name': 'Seychelles'},
    {   'code': 'MG',
        'continent': 'Africa',
        'currency': 'MGA',
        'flag': '🇲🇬',
        'fullName': 'Republic of Madagascar',
        'name': 'Madagascar'},
    {   'code': 'ML',
        'continent': 'Africa',
        'currency': 'XOF',
        'flag': '🇲🇱',
        'fullName': 'Republic of Mali',
        'name': 'Mali'},
    {   'code': 'BF',
        'continent': 'Africa',
        'currency': 'XOF',
        'flag': '🇧🇫',
        'fullName': 'Burkina Faso',
        'name': 'Burkina Faso'},
    {   'code': 'NE',
        'continent': 'Africa',
        'currency': 'XOF',
        'flag': '🇳🇪',
        'fullName': 'Republic of the Niger',
        'name': 'Niger'},
    {   'code': 'GN',
        'continent': 'Africa',
        'currency': 'GNF',
        'flag': '🇬🇳',
        'fullName': 'Republic of Guinea',
        'name': 'Guinea'},
    {   'code': 'SL',
        'continent': 'Africa',
        'currency': 'SLE',
        'flag': '🇸🇱',
        'fullName': 'Republic of Sierra Leone',
        'name': 'Sierra Leone'},
    {   'code': 'LR',
        'continent': 'Africa',
        'currency': 'LRD',
        'flag': '🇱🇷',
        'fullName': 'Republic of Liberia',
        'name': 'Liberia'},
    {   'code': 'TG',
        'continent': 'Africa',
        'currency': 'XOF',
        'flag': '🇹🇬',
        'fullName': 'Togolese Republic',
        'name': 'Togo'},
    {   'code': 'BJ',
        'continent': 'Africa',
        'currency': 'XOF',
        'flag': '🇧🇯',
        'fullName': 'Republic of Benin',
        'name': 'Benin'},
    {   'code': 'CD',
        'continent': 'Africa',
        'currency': 'CDF',
        'flag': '🇨🇩',
        'fullName': 'Democratic Republic of the Congo',
        'name': 'DR Congo'},
    {   'code': 'CG',
        'continent': 'Africa',
        'currency': 'XAF',
        'flag': '🇨🇬',
        'fullName': 'Republic of the Congo',
        'name': 'Congo'},
    {   'code': 'GA',
        'continent': 'Africa',
        'currency': 'XAF',
        'flag': '🇬🇦',
        'fullName': 'Gabonese Republic',
        'name': 'Gabon'},
    {   'code': 'SD',
        'continent': 'Africa',
        'currency': 'SDG',
        'flag': '🇸🇩',
        'fullName': 'Republic of the Sudan',
        'name': 'Sudan'},
    {   'code': 'SS',
        'continent': 'Africa',
        'currency': 'SSP',
        'flag': '🇸🇸',
        'fullName': 'Republic of South Sudan',
        'name': 'South Sudan'},
    {   'code': 'LY',
        'continent': 'Africa',
        'currency': 'LYD',
        'flag': '🇱🇾',
        'fullName': 'State of Libya',
        'name': 'Libya'},
    {   'code': 'SO',
        'continent': 'Africa',
        'currency': 'SOS',
        'flag': '🇸🇴',
        'fullName': 'Federal Republic of Somalia',
        'name': 'Somalia'},
    {   'code': 'MW',
        'continent': 'Africa',
        'currency': 'MWK',
        'flag': '🇲🇼',
        'fullName': 'Republic of Malawi',
        'name': 'Malawi'},
    {   'code': 'GM',
        'continent': 'Africa',
        'currency': 'GMD',
        'flag': '🇬🇲',
        'fullName': 'Republic of the Gambia',
        'name': 'Gambia'},
    {   'code': 'MR',
        'continent': 'Africa',
        'currency': 'MRU',
        'flag': '🇲🇷',
        'fullName': 'Islamic Republic of Mauritania',
        'name': 'Mauritania'},
    {   'code': 'DJ',
        'continent': 'Africa',
        'currency': 'DJF',
        'flag': '🇩🇯',
        'fullName': 'Republic of Djibouti',
        'name': 'Djibouti'},
    {   'code': 'ER',
        'continent': 'Africa',
        'currency': 'ERN',
        'flag': '🇪🇷',
        'fullName': 'State of Eritrea',
        'name': 'Eritrea'},
    {   'code': 'CV',
        'continent': 'Africa',
        'currency': 'CVE',
        'flag': '🇨🇻',
        'fullName': 'Republic of Cabo Verde',
        'name': 'Cape Verde'},
    {   'code': 'ST',
        'continent': 'Africa',
        'currency': 'STN',
        'flag': '🇸🇹',
        'fullName': 'Democratic Republic of São Tomé and Príncipe',
        'name': 'Sao Tome & Principe'},
    {   'code': 'KM',
        'continent': 'Africa',
        'currency': 'KMF',
        'flag': '🇰🇲',
        'fullName': 'Union of the Comoros',
        'name': 'Comoros'},
    {   'code': 'SZ',
        'continent': 'Africa',
        'currency': 'SZL',
        'flag': '🇸🇿',
        'fullName': 'Kingdom of Eswatini',
        'name': 'Eswatini'},
    {   'code': 'LS',
        'continent': 'Africa',
        'currency': 'LSL',
        'flag': '🇱🇸',
        'fullName': 'Kingdom of Lesotho',
        'name': 'Lesotho'},
    {   'code': 'BI',
        'continent': 'Africa',
        'currency': 'BIF',
        'flag': '🇧🇮',
        'fullName': 'Republic of Burundi',
        'name': 'Burundi'},
    {   'code': 'TD',
        'continent': 'Africa',
        'currency': 'XAF',
        'flag': '🇹🇩',
        'fullName': 'Republic of Chad',
        'name': 'Chad'},
    {   'code': 'CF',
        'continent': 'Africa',
        'currency': 'XAF',
        'flag': '🇨🇫',
        'fullName': 'Central African Republic',
        'name': 'Central African Rep'},
    {   'code': 'GQ',
        'continent': 'Africa',
        'currency': 'XAF',
        'flag': '🇬🇶',
        'fullName': 'Republic of Equatorial Guinea',
        'name': 'Equatorial Guinea'},
    {   'code': 'GW',
        'continent': 'Africa',
        'currency': 'XOF',
        'flag': '🇬🇼',
        'fullName': 'Republic of Guinea-Bissau',
        'name': 'Guinea-Bissau'},
    {   'code': 'AU',
        'continent': 'Oceania',
        'currency': 'AUD',
        'flag': '🇦🇺',
        'fullName': 'Commonwealth of Australia',
        'name': 'Australia'},
    {   'code': 'NZ',
        'continent': 'Oceania',
        'currency': 'NZD',
        'flag': '🇳🇿',
        'fullName': 'New Zealand',
        'name': 'New Zealand'},
    {   'code': 'FJ',
        'continent': 'Oceania',
        'currency': 'FJD',
        'flag': '🇫🇯',
        'fullName': 'Republic of Fiji',
        'name': 'Fiji'},
    {   'code': 'PG',
        'continent': 'Oceania',
        'currency': 'PGK',
        'flag': '🇵🇬',
        'fullName': 'Independent State of Papua New Guinea',
        'name': 'Papua New Guinea'},
    {   'code': 'WS',
        'continent': 'Oceania',
        'currency': 'WST',
        'flag': '🇼🇸',
        'fullName': 'Independent State of Samoa',
        'name': 'Samoa'},
    {   'code': 'TO',
        'continent': 'Oceania',
        'currency': 'TOP',
        'flag': '🇹🇴',
        'fullName': 'Kingdom of Tonga',
        'name': 'Tonga'},
    {   'code': 'VU',
        'continent': 'Oceania',
        'currency': 'VUV',
        'flag': '🇻🇺',
        'fullName': 'Republic of Vanuatu',
        'name': 'Vanuatu'},
    {   'code': 'SB',
        'continent': 'Oceania',
        'currency': 'SBD',
        'flag': '🇸🇧',
        'fullName': 'Solomon Islands',
        'name': 'Solomon Islands'},
    {   'code': 'GU',
        'continent': 'Oceania',
        'currency': 'USD',
        'flag': '🇬🇺',
        'fullName': 'Guam',
        'name': 'Guam'},
    {   'code': 'PF',
        'continent': 'Oceania',
        'currency': 'EUR',
        'flag': '🇵🇫',
        'fullName': 'French Polynesia',
        'name': 'French Polynesia'},
    {   'code': 'NC',
        'continent': 'Oceania',
        'currency': 'EUR',
        'flag': '🇳🇨',
        'fullName': 'New Caledonia',
        'name': 'New Caledonia'}]

COUNTRY_BY_CODE = {c["code"]: c for c in ALL_COUNTRIES}
COUNTRY_BY_NAME = {c["name"].upper(): c for c in ALL_COUNTRIES}

def normalize_country_code(val: str) -> str:
    if not val:
        return "AE"
    clean = val.strip().upper()
    if clean in COUNTRY_BY_CODE:
        return clean
    if clean in COUNTRY_BY_NAME:
        return COUNTRY_BY_NAME[clean]["code"]
    aliases = {
        "UAE": "AE", "UNITED ARAB EMIRATES": "AE",
        "USA": "US", "UNITED STATES": "US",
        "UK": "GB", "GREAT BRITAIN": "GB", "ENGLAND": "GB",
        "KSA": "SA", "PHILIPPINES": "PH", "INDIA": "IN",
        "GERMANY": "DE", "FRANCE": "FR", "CANADA": "CA",
        "AUSTRALIA": "AU", "PAKISTAN": "PK", "BANGLADESH": "BD",
        "EGYPT": "EG", "NIGERIA": "NG", "KENYA": "KE",
        "MEXICO": "MX", "BRAZIL": "BR", "CHINA": "CN", "JAPAN": "JP"
    }
    return aliases.get(clean, clean)

GLOBAL_PROVIDERS_CATALOG: List[Dict[str, Any]] = [   {   'estimatedMinutes': 15,
        'feePct': 0.0035,
        'flatFeeUSD': 2.5,
        'fxMarkupPct': 0.0,
        'globalReceive': True,
        'globalSend': True,
        'id': 'wise',
        'logoColor': '#00b9ff',
        'logoText': 'WISE',
        'name': 'Wise (formerly TransferWise)',
        'receiveMethods': ['bank', 'wallet'],
        'requirements': {   'recipient': [   'IBAN / Local Bank Account '
                                             'details or Mobile Wallet'],
                            'sender': [   'Government ID / Passport',
                                          'Bank Account or Debit Card']},
        'speedLabel': '⚡ Instant to 15 mins',
        'transferMethods': ['bank', 'card', 'apple_pay', 'google_pay'],
        'urlTemplate': 'https://wise.com/send?from={from}&to={to}&amount={amount}',
        'website': 'https://wise.com'},
    {   'estimatedMinutes': 5,
        'feePct': 0.005,
        'flatFeeUSD': 4.0,
        'fxMarkupPct': 0.018,
        'globalReceive': True,
        'globalSend': True,
        'id': 'western-union',
        'logoColor': '#ffdd00',
        'logoText': 'WU',
        'name': 'Western Union',
        'receiveMethods': ['cash', 'bank', 'wallet'],
        'requirements': {   'recipient': [   'Government Photo ID & 10-digit '
                                             'MTCN Code'],
                            'sender': [   'National ID / Passport',
                                          'Payment Card or Cash at Agent']},
        'speedLabel': '⚡ Instant Cash Pickup (~5 mins)',
        'transferMethods': ['bank', 'card', 'cash'],
        'urlTemplate': 'https://www.westernunion.com/web/send-money/start?src={from}&dest={to}&amt={amount}',
        'website': 'https://www.westernunion.com'},
    {   'estimatedMinutes': 10,
        'feePct': 0.006,
        'flatFeeUSD': 3.99,
        'fxMarkupPct': 0.019,
        'globalReceive': True,
        'globalSend': True,
        'id': 'moneygram',
        'logoColor': '#ee2a24',
        'logoText': 'MG',
        'name': 'MoneyGram',
        'receiveMethods': ['cash', 'wallet', 'bank'],
        'requirements': {   'recipient': [   '8-digit Reference Number and '
                                             'matching ID'],
                            'sender': [   'Photo Identification',
                                          'Credit/Debit Card or Bank Details']},
        'speedLabel': '⚡ Instant (~10 mins)',
        'transferMethods': ['card', 'bank', 'cash'],
        'urlTemplate': 'https://www.moneygram.com/mgo/us/en/send/money?sendCurrency={from}&receiveCurrency={to}&amount={amount}',
        'website': 'https://www.moneygram.com'},
    {   'estimatedMinutes': 5,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.012,
        'globalReceive': True,
        'globalSend': True,
        'id': 'remitly',
        'logoColor': '#1570ef',
        'logoText': 'REMITLY',
        'name': 'Remitly',
        'receiveMethods': ['bank', 'wallet', 'cash'],
        'requirements': {   'recipient': [   'Official Name matching bank '
                                             'account or cash pickup point'],
                            'sender': [   'Verified Phone Number',
                                          'Emirates ID / SSN / National ID']},
        'speedLabel': '⚡ Express Delivery (~5 mins)',
        'transferMethods': ['card', 'bank'],
        'urlTemplate': 'https://www.remitly.com/send?from={from}&to={to}&amount={amount}',
        'website': 'https://www.remitly.com'},
    {   'estimatedMinutes': 10,
        'feePct': 0.005,
        'flatFeeUSD': 2.99,
        'fxMarkupPct': 0.015,
        'globalReceive': True,
        'globalSend': True,
        'id': 'worldremit',
        'logoColor': '#d92d20',
        'logoText': 'WR',
        'name': 'WorldRemit',
        'receiveMethods': ['wallet', 'bank', 'cash'],
        'requirements': {   'recipient': [   'Mobile Wallet Account Number or '
                                             'Bank Account'],
                            'sender': [   'Identity Verification',
                                          'Visa / Mastercard Debit or Credit']},
        'speedLabel': '🕒 Within 10 mins',
        'transferMethods': ['card', 'bank', 'apple_pay'],
        'urlTemplate': 'https://www.worldremit.com/en/send-money?from={from}&to={to}&amount={amount}',
        'website': 'https://www.worldremit.com'},
    {   'estimatedMinutes': 15,
        'feePct': 0.0055,
        'flatFeeUSD': 3.5,
        'fxMarkupPct': 0.017,
        'globalReceive': True,
        'globalSend': True,
        'id': 'ria',
        'logoColor': '#ff6600',
        'logoText': 'RIA',
        'name': 'Ria Money Transfer',
        'receiveMethods': ['cash', 'bank', 'wallet'],
        'requirements': {   'recipient': [   'Valid Photo ID & PIN order '
                                             'confirmation'],
                            'sender': [   'Government Issued ID',
                                          'Bank Account or Debit Card']},
        'speedLabel': '🕒 Within 15 mins',
        'transferMethods': ['bank', 'card', 'cash'],
        'urlTemplate': 'https://www.riamoneytransfer.com/us/en/send-money?from={from}&to={to}&amount={amount}',
        'website': 'https://www.riamoneytransfer.com'},
    {   'estimatedMinutes': 5,
        'feePct': 0.003,
        'flatFeeUSD': 1.5,
        'fxMarkupPct': 0.0025,
        'globalReceive': True,
        'globalSend': True,
        'id': 'revolut',
        'logoColor': '#191c1f',
        'logoText': 'REV',
        'name': 'Revolut',
        'receiveMethods': ['bank'],
        'requirements': {   'recipient': ['IBAN / SWIFT Bank Account details'],
                            'sender': [   'Revolut App Account with Tier 2 KYC '
                                          'verification']},
        'speedLabel': '⚡ Instant to Same Day',
        'transferMethods': ['bank', 'card'],
        'urlTemplate': 'https://www.revolut.com/international-transfers',
        'website': 'https://www.revolut.com'},
    {   'estimatedMinutes': 360,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.008,
        'globalReceive': True,
        'globalSend': True,
        'id': 'ofx',
        'logoColor': '#027a48',
        'logoText': 'OFX',
        'name': 'OFX Global Currency',
        'receiveMethods': ['bank'],
        'requirements': {   'recipient': ['Recipient Bank Account details'],
                            'sender': [   'OFX Corporate / Individual account',
                                          'Proof of address & Tax ID']},
        'speedLabel': '📅 Same Day (~few hours)',
        'transferMethods': ['bank'],
        'urlTemplate': 'https://www.ofx.com/en-us/money-transfer?from={from}&to={to}&amount={amount}',
        'website': 'https://www.ofx.com'},
    {   'estimatedMinutes': 60,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.011,
        'globalReceive': True,
        'globalSend': True,
        'id': 'xe',
        'logoColor': '#0052cc',
        'logoText': 'XE',
        'name': 'Xe Money Transfer',
        'receiveMethods': ['bank', 'cash'],
        'requirements': {   'recipient': [   'Bank Account details or Pickup '
                                             'Location'],
                            'sender': [   'Government ID Verification',
                                          'Direct Bank Account ACH or Card']},
        'speedLabel': '🕒 Within 60 mins',
        'transferMethods': ['bank', 'card'],
        'urlTemplate': 'https://www.xe.com/send-money?from={from}&to={to}&amount={amount}',
        'website': 'https://www.xe.com'},
    {   'estimatedMinutes': 5,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.007,
        'globalReceive': True,
        'globalSend': True,
        'id': 'taptap-send',
        'logoColor': '#10b981',
        'logoText': 'TAPTAP',
        'name': 'TapTap Send',
        'receiveMethods': ['wallet', 'bank'],
        'requirements': {   'recipient': [   'Mobile Wallet (GCash, Maya, '
                                             'M-Pesa, Wave)'],
                            'sender': [   'Valid Mobile Number',
                                          'Emirates ID / EU / US Resident '
                                          'Debit Card']},
        'speedLabel': '⚡ Instant (~5 mins)',
        'transferMethods': ['card', 'wallet'],
        'urlTemplate': 'https://www.taptapsend.com/corridors/{from}-to-{to}',
        'website': 'https://www.taptapsend.com'},
    {   'estimatedMinutes': 15,
        'feePct': 0.003,
        'flatFeeUSD': 2.0,
        'fxMarkupPct': 0.005,
        'globalReceive': True,
        'globalSend': True,
        'id': 'instarem',
        'logoColor': '#6366f1',
        'logoText': 'INSTA',
        'name': 'Instarem',
        'receiveMethods': ['bank'],
        'requirements': {   'recipient': [   'Bank Account Name and Account / '
                                             'IBAN'],
                            'sender': [   'National ID / Passport Verification',
                                          'Bank Account ACH or Debit']},
        'speedLabel': '🕒 Within 15 mins',
        'transferMethods': ['bank', 'card'],
        'urlTemplate': 'https://www.instarem.com/transfer?from={from}&to={to}&amount={amount}',
        'website': 'https://www.instarem.com'},
    {   'estimatedMinutes': 10,
        'feePct': 0.0,
        'flatFeeUSD': 2.0,
        'fxMarkupPct': 0.012,
        'globalReceive': True,
        'globalSend': True,
        'id': 'paysend',
        'logoColor': '#7c3aed',
        'logoText': 'PAYSEND',
        'name': 'Paysend',
        'receiveMethods': ['card', 'bank', 'wallet'],
        'requirements': {   'recipient': [   '16-digit Card Number or Bank '
                                             'Details'],
                            'sender': [   'Debit or Credit Card details',
                                          'Verified Phone']},
        'speedLabel': '🕒 Within 10 mins',
        'transferMethods': ['card', 'bank'],
        'urlTemplate': 'https://www.paysend.com/send-money?from={from}&to={to}&amount={amount}',
        'website': 'https://www.paysend.com'},
    {   'estimatedMinutes': 3,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.013,
        'globalReceive': True,
        'globalSend': True,
        'id': 'sendwave',
        'logoColor': '#0ea5e9',
        'logoText': 'WAVE',
        'name': 'Sendwave',
        'receiveMethods': ['wallet', 'bank'],
        'requirements': {   'recipient': ['Mobile Wallet or Bank Account'],
                            'sender': ['Debit Card', 'SMS verification']},
        'speedLabel': '⚡ Instant (~3 mins)',
        'transferMethods': ['card'],
        'urlTemplate': 'https://www.sendwave.com/send?from={from}&to={to}&amount={amount}',
        'website': 'https://www.sendwave.com'},
    {   'estimatedMinutes': 10,
        'feePct': 0.004,
        'flatFeeUSD': 2.99,
        'fxMarkupPct': 0.016,
        'globalReceive': True,
        'globalSend': True,
        'id': 'xoom',
        'logoColor': '#0070ba',
        'logoText': 'XOOM',
        'name': 'Xoom (PayPal)',
        'receiveMethods': ['bank', 'cash', 'wallet'],
        'requirements': {   'recipient': [   'Bank Account or Cash Pickup '
                                             'Government ID'],
                            'sender': [   'PayPal Account or Debit Card',
                                          'ID Verification']},
        'speedLabel': '⚡ Instant to Bank/Pickup (~10 mins)',
        'transferMethods': ['bank', 'card', 'wallet'],
        'urlTemplate': 'https://www.xoom.com/send-money?from={from}&to={to}&amount={amount}',
        'website': 'https://www.xoom.com'},
    {   'estimatedMinutes': 30,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.014,
        'globalReceive': True,
        'globalSend': True,
        'id': 'skrill',
        'logoColor': '#811653',
        'logoText': 'SKRILL',
        'name': 'Skrill Money Transfer',
        'receiveMethods': ['bank', 'wallet'],
        'requirements': {   'recipient': [   'Bank Account details or Mobile '
                                             'Wallet'],
                            'sender': ['Skrill Account & Email Verification']},
        'speedLabel': '🕒 Within 30 mins',
        'transferMethods': ['card', 'bank'],
        'urlTemplate': 'https://www.skrill.com/en/transfer-money',
        'website': 'https://www.skrill.com'},
    {   'estimatedMinutes': 240,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.0065,
        'globalReceive': True,
        'globalSend': True,
        'id': 'currencies-direct',
        'logoColor': '#e11d48',
        'logoText': 'CD',
        'name': 'Currencies Direct',
        'receiveMethods': ['bank'],
        'requirements': {   'recipient': ['Full Bank Account SWIFT / IBAN'],
                            'sender': [   'ID & Address Verification',
                                          'Source of Funds for large sums']},
        'speedLabel': '📅 Same Day (~4-8 hours)',
        'transferMethods': ['bank'],
        'urlTemplate': 'https://www.currenciesdirect.com/en',
        'website': 'https://www.currenciesdirect.com'},
    {   'estimatedMinutes': 300,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.006,
        'globalReceive': True,
        'globalSend': True,
        'id': 'torfx',
        'logoColor': '#2563eb',
        'logoText': 'TORFX',
        'name': 'TorFX',
        'receiveMethods': ['bank'],
        'requirements': {   'recipient': ['Recipient Bank Account details'],
                            'sender': [   'Official Photo ID',
                                          'Bank Wire Details']},
        'speedLabel': '📅 Same Day Delivery',
        'transferMethods': ['bank'],
        'urlTemplate': 'https://www.torfx.com/transfers',
        'website': 'https://www.torfx.com'},
    {   'estimatedMinutes': 1440,
        'feePct': 0.0,
        'flatFeeUSD': 3.0,
        'fxMarkupPct': 0.0045,
        'globalReceive': True,
        'globalSend': True,
        'id': 'currencyfair',
        'logoColor': '#f59e0b',
        'logoText': 'CFAIR',
        'name': 'CurrencyFair',
        'receiveMethods': ['bank'],
        'requirements': {   'recipient': ['Bank Account Details'],
                            'sender': [   'Passport / National ID',
                                          'Proof of Residency']},
        'speedLabel': '🗓️ 1 Business Day',
        'transferMethods': ['bank'],
        'urlTemplate': 'https://www.currencyfair.com/send-money',
        'website': 'https://www.currencyfair.com'},
    {   'estimatedMinutes': 30,
        'feePct': 0.0,
        'flatFeeUSD': 4.1,
        'fxMarkupPct': 0.007,
        'globalReceive': True,
        'globalSend': True,
        'id': 'al-ansari',
        'logoColor': '#c2410c',
        'logoText': 'ALANSARI',
        'name': 'Al Ansari Exchange',
        'receiveMethods': ['bank', 'cash', 'wallet'],
        'requirements': {   'recipient': [   'Cebuana / Muthoot pickup or Bank '
                                             'Account'],
                            'sender': [   'Emirates ID / GCC National ID',
                                          'Debit Card / Cash']},
        'speedLabel': '🕒 Within 30 mins',
        'transferMethods': ['bank', 'card', 'cash'],
        'urlTemplate': 'https://alansariexchange.com/online-remittance',
        'website': 'https://alansariexchange.com'},
    {   'estimatedMinutes': 45,
        'feePct': 0.0,
        'flatFeeUSD': 3.3,
        'fxMarkupPct': 0.008,
        'globalReceive': True,
        'globalSend': True,
        'id': 'lulu-exchange',
        'logoColor': '#059669',
        'logoText': 'LULU',
        'name': 'LuLu Exchange (LuLu Money)',
        'receiveMethods': ['bank', 'cash', 'wallet'],
        'requirements': {   'recipient': ['Cash Pickup or Bank Account'],
                            'sender': [   'Emirates ID / GCC ID',
                                          'Local Bank Account or Debit Card']},
        'speedLabel': '🕒 Within 45 mins',
        'transferMethods': ['bank', 'card'],
        'urlTemplate': 'https://www.lulumoney.com',
        'website': 'https://www.luluexchange.com'},
    {   'estimatedMinutes': 10,
        'feePct': 0.0,
        'flatFeeUSD': 2.05,
        'fxMarkupPct': 0.006,
        'globalReceive': True,
        'globalSend': True,
        'id': 'hubpay',
        'logoColor': '#0284c7',
        'logoText': 'HUBPAY',
        'name': 'Hubpay UAE',
        'receiveMethods': ['bank', 'wallet'],
        'requirements': {   'recipient': [   'GCash, bKash, Easypaisa or Bank '
                                             'Account'],
                            'sender': [   'UAE Pass / Emirates ID Digital KYC',
                                          'UAE Bank Account']},
        'speedLabel': '🕒 Within 10 mins',
        'transferMethods': ['bank', 'wallet'],
        'urlTemplate': 'https://www.hubpay.com/remittance',
        'website': 'https://www.hubpay.com'},
    {   'estimatedMinutes': 5,
        'feePct': 0.0,
        'flatFeeUSD': 1.35,
        'fxMarkupPct': 0.009,
        'globalReceive': True,
        'globalSend': True,
        'id': 'pyypl',
        'logoColor': '#8b5cf6',
        'logoText': 'PYYPL',
        'name': 'Pyypl GCC',
        'receiveMethods': ['bank', 'wallet'],
        'requirements': {   'recipient': ['Mobile Wallet or Bank Account'],
                            'sender': [   'Pyypl App Account',
                                          'Emirates ID / National ID']},
        'speedLabel': '⚡ Instant (~5 mins)',
        'transferMethods': ['card', 'wallet'],
        'urlTemplate': 'https://www.pyypl.com/features/send-money',
        'website': 'https://www.pyypl.com'},
    {   'estimatedMinutes': 5,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.0085,
        'globalReceive': True,
        'globalSend': True,
        'id': 'lemfi',
        'logoColor': '#ec4899',
        'logoText': 'LEMFI',
        'name': 'LemFi',
        'receiveMethods': ['bank', 'wallet'],
        'requirements': {   'recipient': [   'Local bank account number or '
                                             'Mobile Money'],
                            'sender': [   'Government ID / Visa verification',
                                          'Local debit card']},
        'speedLabel': '⚡ Instant (~5 mins)',
        'transferMethods': ['bank', 'card'],
        'urlTemplate': 'https://lemfi.com/send',
        'website': 'https://lemfi.com'},
    {   'estimatedMinutes': 5,
        'feePct': 0.0,
        'flatFeeUSD': 1.0,
        'fxMarkupPct': 0.01,
        'globalReceive': True,
        'globalSend': True,
        'id': 'flutterwave',
        'logoColor': '#f97316',
        'logoText': 'FLUTTER',
        'name': 'Flutterwave Send',
        'receiveMethods': ['bank', 'wallet'],
        'requirements': {   'recipient': [   'Bank Account details or Mobile '
                                             'Money Wallet'],
                            'sender': [   'Phone number & Debit Card',
                                          'Photo ID Verification']},
        'speedLabel': '⚡ Instant (~5 mins)',
        'transferMethods': ['card', 'bank'],
        'urlTemplate': 'https://send.flutterwave.com',
        'website': 'https://send.flutterwave.com'},
    {   'estimatedMinutes': 2,
        'feePct': 0.0,
        'flatFeeUSD': 0.0,
        'fxMarkupPct': 0.011,
        'globalReceive': True,
        'globalSend': True,
        'id': 'chipper-cash',
        'logoColor': '#14b8a6',
        'logoText': 'CHIPPER',
        'name': 'Chipper Cash',
        'receiveMethods': ['wallet', 'bank'],
        'requirements': {   'recipient': [   'Chipper @Tag, Mobile Money or '
                                             'Bank Account'],
                            'sender': ['Chipper Account', 'Government ID']},
        'speedLabel': '⚡ Instant (~2 mins)',
        'transferMethods': ['wallet', 'card'],
        'urlTemplate': 'https://chippercash.com',
        'website': 'https://chippercash.com'}]
